// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Title     string
	Body      pgtype.Text
	Priority  string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
