// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	ListTasksByTenant(ctx context.Context, arg ListTasksByTenantParams) ([]Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
