// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (tenant_id, title, body, priority, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, title, body, priority, status, created_at, updated_at
`

type CreateTaskParams struct {
	TenantID pgtype.UUID
	Title    string
	Body     pgtype.Text
	Priority string
	Status   string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TenantID,
		arg.Title,
		arg.Body,
		arg.Priority,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Body,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND tenant_id = $2
`

type DeleteTaskParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.TenantID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, tenant_id, title, body, priority, status, created_at, updated_at
FROM tasks
WHERE id = $1 AND tenant_id = $2
`

type GetTaskParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.TenantID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Body,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByTenant = `-- name: ListTasksByTenant :many
SELECT id, tenant_id, title, body, priority, status, created_at, updated_at
FROM tasks
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByTenantParams struct {
	TenantID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListTasksByTenant(ctx context.Context, arg ListTasksByTenantParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Body,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3, body = $4, priority = $5, status = $6, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, title, body, priority, status, created_at, updated_at
`

type UpdateTaskParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	Title    string
	Body     pgtype.Text
	Priority string
	Status   string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Body,
		arg.Priority,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Body,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
