FROM postgres:15-alpine

RUN apk add --no-cache bash

COPY infra/migrations/ /migrations/
COPY infra/prod/run_migrations.sh /run_migrations.sh
RUN chmod +x /run_migrations.sh

ENV PGHOST=postgres
ENV PGUSER=postgres
ENV PGDATABASE=arc_db

ENTRYPOINT ["/run_migrations.sh"]
