// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (event_id, aggregate_type, aggregate_id, actor_id, event_type, payload)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (event_id) DO NOTHING
`

type InsertAuditLogParams struct {
	EventID       pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	ActorID       pgtype.UUID
	EventType     string
	Payload       []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.EventID,
		arg.AggregateType,
		arg.AggregateID,
		arg.ActorID,
		arg.EventType,
		arg.Payload,
	)
	return err
}
