// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             pgtype.UUID
	EventID        pgtype.UUID
	OrganizationID pgtype.UUID
	SourceService  string
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
	ActorID        pgtype.UUID  // nullable — not all events are human-initiated
	CreatedAt      pgtype.Timestamptz
}
