// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	EventID       pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	ActorID       pgtype.UUID
	EventType     string
	Payload       []byte
	RecordedAt    pgtype.Timestamptz
}
