// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
}

var _ Querier = (*Queries)(nil)
