// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dictionary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDictionaryItem = `-- name: CreateDictionaryItem :one
INSERT INTO data_dictionary (id, organization_id, name, category, sensitivity, third_party_rule_id, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at
`

type CreateDictionaryItemParams struct {
	ID               pgtype.UUID `json:"id"`
	OrganizationID   pgtype.UUID `json:"organization_id"`
	Name             string      `json:"name"`
	Category         pgtype.Text `json:"category"`
	Sensitivity      pgtype.Text `json:"sensitivity"`
	ThirdPartyRuleID pgtype.Text `json:"third_party_rule_id"`
	Active           pgtype.Bool `json:"active"`
}

func (q *Queries) CreateDictionaryItem(ctx context.Context, arg CreateDictionaryItemParams) (DataDictionary, error) {
	row := q.db.QueryRow(ctx, createDictionaryItem,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Category,
		arg.Sensitivity,
		arg.ThirdPartyRuleID,
		arg.Active,
	)
	var i DataDictionary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Category,
		&i.Sensitivity,
		&i.ThirdPartyRuleID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDictionaryItem = `-- name: GetDictionaryItem :one
SELECT id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at FROM data_dictionary
WHERE id = $1 AND organization_id = $2
`

type GetDictionaryItemParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetDictionaryItem(ctx context.Context, arg GetDictionaryItemParams) (DataDictionary, error) {
	row := q.db.QueryRow(ctx, getDictionaryItem, arg.ID, arg.OrganizationID)
	var i DataDictionary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Category,
		&i.Sensitivity,
		&i.ThirdPartyRuleID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDictionaryItemByName = `-- name: GetDictionaryItemByName :one
SELECT id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at FROM data_dictionary
WHERE organization_id = $1 AND name = $2
`

type GetDictionaryItemByNameParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
}

func (q *Queries) GetDictionaryItemByName(ctx context.Context, arg GetDictionaryItemByNameParams) (DataDictionary, error) {
	row := q.db.QueryRow(ctx, getDictionaryItemByName, arg.OrganizationID, arg.Name)
	var i DataDictionary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Category,
		&i.Sensitivity,
		&i.ThirdPartyRuleID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDictionaryItems = `-- name: ListDictionaryItems :many
SELECT id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at FROM data_dictionary
WHERE organization_id = $1
ORDER BY name ASC
`

func (q *Queries) ListDictionaryItems(ctx context.Context, organizationID pgtype.UUID) ([]DataDictionary, error) {
	rows, err := q.db.Query(ctx, listDictionaryItems, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataDictionary
	for rows.Next() {
		var i DataDictionary
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Category,
			&i.Sensitivity,
			&i.ThirdPartyRuleID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDictionaryItem = `-- name: UpdateDictionaryItem :one
UPDATE data_dictionary
SET name = $3, category = $4, sensitivity = $5, active = $6, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at
`

type UpdateDictionaryItemParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Category       pgtype.Text `json:"category"`
	Sensitivity    pgtype.Text `json:"sensitivity"`
	Active         pgtype.Bool `json:"active"`
}

func (q *Queries) UpdateDictionaryItem(ctx context.Context, arg UpdateDictionaryItemParams) (DataDictionary, error) {
	row := q.db.QueryRow(ctx, updateDictionaryItem,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Category,
		arg.Sensitivity,
		arg.Active,
	)
	var i DataDictionary
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Category,
		&i.Sensitivity,
		&i.ThirdPartyRuleID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
