// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// ── Data Dictionary ───────────────────────────────────────────────────────

const createDictionaryItem = `INSERT INTO data_dictionary (id, organization_id, name, category, sensitivity, third_party_rule_id, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at`

type CreateDictionaryItemParams struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Name             string
	Category         pgtype.Text
	Sensitivity      pgtype.Text
	ThirdPartyRuleID pgtype.Text
	Active           pgtype.Bool
}

func (q *Queries) CreateDictionaryItem(ctx context.Context, arg CreateDictionaryItemParams) (DataDictionaryItem, error) {
	row := q.db.QueryRow(ctx, createDictionaryItem,
		arg.ID, arg.OrganizationID, arg.Name, arg.Category, arg.Sensitivity, arg.ThirdPartyRuleID, arg.Active)
	var i DataDictionaryItem
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Name, &i.Category, &i.Sensitivity,
		&i.ThirdPartyRuleID, &i.Active, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getDictionaryItem = `SELECT id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at
FROM data_dictionary WHERE id = $1 AND organization_id = $2`

type GetDictionaryItemParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetDictionaryItem(ctx context.Context, arg GetDictionaryItemParams) (DataDictionaryItem, error) {
	row := q.db.QueryRow(ctx, getDictionaryItem, arg.ID, arg.OrganizationID)
	var i DataDictionaryItem
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Name, &i.Category, &i.Sensitivity,
		&i.ThirdPartyRuleID, &i.Active, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getDictionaryItemByName = `SELECT id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at
FROM data_dictionary WHERE organization_id = $1 AND name = $2`

type GetDictionaryItemByNameParams struct {
	OrganizationID pgtype.UUID
	Name           string
}

func (q *Queries) GetDictionaryItemByName(ctx context.Context, arg GetDictionaryItemByNameParams) (DataDictionaryItem, error) {
	row := q.db.QueryRow(ctx, getDictionaryItemByName, arg.OrganizationID, arg.Name)
	var i DataDictionaryItem
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Name, &i.Category, &i.Sensitivity,
		&i.ThirdPartyRuleID, &i.Active, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listDictionaryItems = `SELECT id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at
FROM data_dictionary WHERE organization_id = $1 ORDER BY name ASC`

func (q *Queries) ListDictionaryItems(ctx context.Context, organizationID interface{}) ([]DataDictionaryItem, error) {
	rows, err := q.db.Query(ctx, listDictionaryItems, organizationID)
	if err != nil {
		return nil, err
	}
	pgRows := rows.(pgx.Rows)
	defer pgRows.Close()
	var items []DataDictionaryItem
	for pgRows.Next() {
		var i DataDictionaryItem
		if err := pgRows.Scan(
			&i.ID, &i.OrganizationID, &i.Name, &i.Category, &i.Sensitivity,
			&i.ThirdPartyRuleID, &i.Active, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, pgRows.Err()
}

const updateDictionaryItem = `UPDATE data_dictionary
SET name = $3, category = $4, sensitivity = $5, active = $6, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, category, sensitivity, third_party_rule_id, active, created_at, updated_at`

type UpdateDictionaryItemParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Category       pgtype.Text
	Sensitivity    pgtype.Text
	Active         pgtype.Bool
}

func (q *Queries) UpdateDictionaryItem(ctx context.Context, arg UpdateDictionaryItemParams) (DataDictionaryItem, error) {
	row := q.db.QueryRow(ctx, updateDictionaryItem,
		arg.ID, arg.OrganizationID, arg.Name, arg.Category, arg.Sensitivity, arg.Active)
	var i DataDictionaryItem
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Name, &i.Category, &i.Sensitivity,
		&i.ThirdPartyRuleID, &i.Active, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

// ── Scan Jobs ─────────────────────────────────────────────────────────────

const createScanJob = `INSERT INTO scan_jobs (id, organization_id, third_party_job_id, source_name, status, findings_synced)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, third_party_job_id, source_name, status, findings_synced, created_at, updated_at`

type CreateScanJobParams struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	ThirdPartyJobID string
	SourceName      string
	Status          string
	FindingsSynced  pgtype.Bool
}

func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, createScanJob,
		arg.ID, arg.OrganizationID, arg.ThirdPartyJobID, arg.SourceName, arg.Status, arg.FindingsSynced)
	var i ScanJob
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.ThirdPartyJobID, &i.SourceName,
		&i.Status, &i.FindingsSynced, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getScanJob = `SELECT id, organization_id, third_party_job_id, source_name, status, findings_synced, created_at, updated_at
FROM scan_jobs WHERE id = $1 AND organization_id = $2`

type GetScanJobParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetScanJob(ctx context.Context, arg GetScanJobParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, getScanJob, arg.ID, arg.OrganizationID)
	var i ScanJob
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.ThirdPartyJobID, &i.SourceName,
		&i.Status, &i.FindingsSynced, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listPendingScanJobs = `SELECT id, organization_id, third_party_job_id, source_name, status, findings_synced, created_at, updated_at
FROM scan_jobs WHERE status IN ('PENDING', 'RUNNING') ORDER BY created_at ASC`

func (q *Queries) ListPendingScanJobs(ctx context.Context) ([]ScanJob, error) {
	rows, err := q.db.Query(ctx, listPendingScanJobs)
	if err != nil {
		return nil, err
	}
	pgRows := rows.(pgx.Rows)
	defer pgRows.Close()
	var items []ScanJob
	for pgRows.Next() {
		var i ScanJob
		if err := pgRows.Scan(
			&i.ID, &i.OrganizationID, &i.ThirdPartyJobID, &i.SourceName,
			&i.Status, &i.FindingsSynced, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, pgRows.Err()
}

const updateScanJobStatus = `UPDATE scan_jobs
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, third_party_job_id, source_name, status, findings_synced, created_at, updated_at`

type UpdateScanJobStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, updateScanJobStatus, arg.ID, arg.Status)
	var i ScanJob
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.ThirdPartyJobID, &i.SourceName,
		&i.Status, &i.FindingsSynced, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const markScanJobSynced = `UPDATE scan_jobs
SET findings_synced = true, status = 'COMPLETED', updated_at = NOW()
WHERE id = $1`

func (q *Queries) MarkScanJobSynced(ctx context.Context, id interface{}) error {
	_, err := q.db.Exec(ctx, markScanJobSynced, id)
	return err
}

// ── Outbox ────────────────────────────────────────────────────────────────

const insertOutboxEvent = `INSERT INTO outbox_events (id, organization_id, aggregate_type, aggregate_id, event_type, payload)
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (id) DO NOTHING`

type InsertOutboxEventParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID, arg.OrganizationID, arg.AggregateType, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}
