// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
}

type DataDictionaryItem struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Name             string
	Category         pgtype.Text
	Sensitivity      pgtype.Text
	ThirdPartyRuleID pgtype.Text
	Active           pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ScanJob struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	ThirdPartyJobID  string
	SourceName       string
	Status           string
	FindingsSynced   pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
