// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDictionaryItem(ctx context.Context, arg CreateDictionaryItemParams) (DataDictionary, error)
	CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error)
	GetDictionaryItem(ctx context.Context, arg GetDictionaryItemParams) (DataDictionary, error)
	GetDictionaryItemByName(ctx context.Context, arg GetDictionaryItemByNameParams) (DataDictionary, error)
	GetScanJob(ctx context.Context, arg GetScanJobParams) (ScanJob, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListDictionaryItems(ctx context.Context, organizationID pgtype.UUID) ([]DataDictionary, error)
	ListPendingScanJobs(ctx context.Context) ([]ScanJob, error)
	MarkScanJobSynced(ctx context.Context, id pgtype.UUID) error
	UpdateDictionaryItem(ctx context.Context, arg UpdateDictionaryItemParams) (DataDictionary, error)
	UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) (ScanJob, error)
}

var _ Querier = (*Queries)(nil)
