// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import "context"

type Querier interface {
	// Data Dictionary
	CreateDictionaryItem(ctx context.Context, arg CreateDictionaryItemParams) (DataDictionaryItem, error)
	GetDictionaryItem(ctx context.Context, arg GetDictionaryItemParams) (DataDictionaryItem, error)
	GetDictionaryItemByName(ctx context.Context, arg GetDictionaryItemByNameParams) (DataDictionaryItem, error)
	ListDictionaryItems(ctx context.Context, organizationID interface{}) ([]DataDictionaryItem, error)
	UpdateDictionaryItem(ctx context.Context, arg UpdateDictionaryItemParams) (DataDictionaryItem, error)

	// Scan Jobs
	CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error)
	GetScanJob(ctx context.Context, arg GetScanJobParams) (ScanJob, error)
	ListPendingScanJobs(ctx context.Context) ([]ScanJob, error)
	UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) (ScanJob, error)
	MarkScanJobSynced(ctx context.Context, id interface{}) error

	// Outbox
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
