// Code generated by MockGen. DO NOT EDIT.
// Source: apps/iam-service/internal/repository/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=apps/iam-service/internal/repository/db/querier.go -destination=apps/iam-service/internal/repository/mock/querier_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	db "github.com/arc-self/apps/iam-service/internal/repository/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AssignUserRole mocks base method.
func (m *MockQuerier) AssignUserRole(ctx context.Context, arg db.AssignUserRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUserRole indicates an expected call of AssignUserRole.
func (mr *MockQuerierMockRecorder) AssignUserRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserRole", reflect.TypeOf((*MockQuerier)(nil).AssignUserRole), ctx, arg)
}

// CheckUserPermission mocks base method.
func (m *MockQuerier) CheckUserPermission(ctx context.Context, arg db.CheckUserPermissionParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPermission", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserPermission indicates an expected call of CheckUserPermission.
func (mr *MockQuerierMockRecorder) CheckUserPermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPermission", reflect.TypeOf((*MockQuerier)(nil).CheckUserPermission), ctx, arg)
}

// GetDefaultRole mocks base method.
func (m *MockQuerier) GetDefaultRole(ctx context.Context, organizationID pgtype.UUID) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultRole", ctx, organizationID)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultRole indicates an expected call of GetDefaultRole.
func (mr *MockQuerierMockRecorder) GetDefaultRole(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultRole", reflect.TypeOf((*MockQuerier)(nil).GetDefaultRole), ctx, organizationID)
}

// GetOrganizationByName mocks base method.
func (m *MockQuerier) GetOrganizationByName(ctx context.Context, name string) (db.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByName", ctx, name)
	ret0, _ := ret[0].(db.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByName indicates an expected call of GetOrganizationByName.
func (mr *MockQuerierMockRecorder) GetOrganizationByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByName", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationByName), ctx, name)
}

// GetUserPermissionsInOrg mocks base method.
func (m *MockQuerier) GetUserPermissionsInOrg(ctx context.Context, arg db.GetUserPermissionsInOrgParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissionsInOrg", ctx, arg)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissionsInOrg indicates an expected call of GetUserPermissionsInOrg.
func (mr *MockQuerierMockRecorder) GetUserPermissionsInOrg(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissionsInOrg", reflect.TypeOf((*MockQuerier)(nil).GetUserPermissionsInOrg), ctx, arg)
}

// UpsertUser mocks base method.
func (m *MockQuerier) UpsertUser(ctx context.Context, arg db.UpsertUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockQuerierMockRecorder) UpsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockQuerier)(nil).UpsertUser), ctx, arg)
}
