// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/db/querier.go -destination=internal/repository/mock/querier_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	db "github.com/arc-self/apps/iam-service/internal/repository/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// AddUserRole mocks base method.
func (m *MockQuerier) AddUserRole(ctx context.Context, arg db.AddUserRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserRole indicates an expected call of AddUserRole.
func (mr *MockQuerierMockRecorder) AddUserRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserRole", reflect.TypeOf((*MockQuerier)(nil).AddUserRole), ctx, arg)
}

// AssignUserRole mocks base method.
func (m *MockQuerier) AssignUserRole(ctx context.Context, arg db.AssignUserRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUserRole indicates an expected call of AssignUserRole.
func (mr *MockQuerierMockRecorder) AssignUserRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserRole", reflect.TypeOf((*MockQuerier)(nil).AssignUserRole), ctx, arg)
}

// CheckUserPermission mocks base method.
func (m *MockQuerier) CheckUserPermission(ctx context.Context, arg db.CheckUserPermissionParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserPermission", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserPermission indicates an expected call of CheckUserPermission.
func (mr *MockQuerierMockRecorder) CheckUserPermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserPermission", reflect.TypeOf((*MockQuerier)(nil).CheckUserPermission), ctx, arg)
}

// CreateApiKey mocks base method.
func (m *MockQuerier) CreateApiKey(ctx context.Context, arg db.CreateApiKeyParams) (db.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateApiKey", ctx, arg)
	ret0, _ := ret[0].(db.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateApiKey indicates an expected call of CreateApiKey.
func (mr *MockQuerierMockRecorder) CreateApiKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateApiKey", reflect.TypeOf((*MockQuerier)(nil).CreateApiKey), ctx, arg)
}

// CreateRole mocks base method.
func (m *MockQuerier) CreateRole(ctx context.Context, arg db.CreateRoleParams) (db.CreateRoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, arg)
	ret0, _ := ret[0].(db.CreateRoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockQuerierMockRecorder) CreateRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockQuerier)(nil).CreateRole), ctx, arg)
}

// DeleteRolePermissions mocks base method.
func (m *MockQuerier) DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRolePermissions", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRolePermissions indicates an expected call of DeleteRolePermissions.
func (mr *MockQuerierMockRecorder) DeleteRolePermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRolePermissions", reflect.TypeOf((*MockQuerier)(nil).DeleteRolePermissions), ctx, roleID)
}

// GetApiKeyByHash mocks base method.
func (m *MockQuerier) GetApiKeyByHash(ctx context.Context, keyHash string) (db.GetApiKeyByHashRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeyByHash", ctx, keyHash)
	ret0, _ := ret[0].(db.GetApiKeyByHashRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeyByHash indicates an expected call of GetApiKeyByHash.
func (mr *MockQuerierMockRecorder) GetApiKeyByHash(ctx, keyHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeyByHash", reflect.TypeOf((*MockQuerier)(nil).GetApiKeyByHash), ctx, keyHash)
}

// GetDefaultRole mocks base method.
func (m *MockQuerier) GetDefaultRole(ctx context.Context, organizationID pgtype.UUID) (db.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultRole", ctx, organizationID)
	ret0, _ := ret[0].(db.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultRole indicates an expected call of GetDefaultRole.
func (mr *MockQuerierMockRecorder) GetDefaultRole(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultRole", reflect.TypeOf((*MockQuerier)(nil).GetDefaultRole), ctx, organizationID)
}

// GetOrganizationByName mocks base method.
func (m *MockQuerier) GetOrganizationByName(ctx context.Context, name string) (db.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByName", ctx, name)
	ret0, _ := ret[0].(db.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByName indicates an expected call of GetOrganizationByName.
func (mr *MockQuerierMockRecorder) GetOrganizationByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByName", reflect.TypeOf((*MockQuerier)(nil).GetOrganizationByName), ctx, name)
}

// GetRolePermissions mocks base method.
func (m *MockQuerier) GetRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockQuerierMockRecorder) GetRolePermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockQuerier)(nil).GetRolePermissions), ctx, roleID)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockQuerier) GetUserByID(ctx context.Context, id pgtype.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockQuerierMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockQuerier)(nil).GetUserByID), ctx, id)
}

// GetUserOrganizations mocks base method.
func (m *MockQuerier) GetUserOrganizations(ctx context.Context, userID pgtype.UUID) ([]db.GetUserOrganizationsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrganizations", ctx, userID)
	ret0, _ := ret[0].([]db.GetUserOrganizationsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrganizations indicates an expected call of GetUserOrganizations.
func (mr *MockQuerierMockRecorder) GetUserOrganizations(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrganizations", reflect.TypeOf((*MockQuerier)(nil).GetUserOrganizations), ctx, userID)
}

// GetUserPermissionsInOrg mocks base method.
func (m *MockQuerier) GetUserPermissionsInOrg(ctx context.Context, arg db.GetUserPermissionsInOrgParams) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissionsInOrg", ctx, arg)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissionsInOrg indicates an expected call of GetUserPermissionsInOrg.
func (mr *MockQuerierMockRecorder) GetUserPermissionsInOrg(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissionsInOrg", reflect.TypeOf((*MockQuerier)(nil).GetUserPermissionsInOrg), ctx, arg)
}

// InsertRolePermission mocks base method.
func (m *MockQuerier) InsertRolePermission(ctx context.Context, arg db.InsertRolePermissionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRolePermission", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRolePermission indicates an expected call of InsertRolePermission.
func (mr *MockQuerierMockRecorder) InsertRolePermission(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRolePermission", reflect.TypeOf((*MockQuerier)(nil).InsertRolePermission), ctx, arg)
}

// ListApiKeys mocks base method.
func (m *MockQuerier) ListApiKeys(ctx context.Context, organizationID pgtype.UUID) ([]db.ListApiKeysRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListApiKeys", ctx, organizationID)
	ret0, _ := ret[0].([]db.ListApiKeysRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListApiKeys indicates an expected call of ListApiKeys.
func (mr *MockQuerierMockRecorder) ListApiKeys(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListApiKeys", reflect.TypeOf((*MockQuerier)(nil).ListApiKeys), ctx, organizationID)
}

// ListOrganizationUsers mocks base method.
func (m *MockQuerier) ListOrganizationUsers(ctx context.Context, organizationID pgtype.UUID) ([]db.ListOrganizationUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizationUsers", ctx, organizationID)
	ret0, _ := ret[0].([]db.ListOrganizationUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationUsers indicates an expected call of ListOrganizationUsers.
func (mr *MockQuerierMockRecorder) ListOrganizationUsers(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationUsers", reflect.TypeOf((*MockQuerier)(nil).ListOrganizationUsers), ctx, organizationID)
}

// ListPermissions mocks base method.
func (m *MockQuerier) ListPermissions(ctx context.Context) ([]db.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions", ctx)
	ret0, _ := ret[0].([]db.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockQuerierMockRecorder) ListPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockQuerier)(nil).ListPermissions), ctx)
}

// ListRolesForOrganization mocks base method.
func (m *MockQuerier) ListRolesForOrganization(ctx context.Context, organizationID pgtype.UUID) ([]db.ListRolesForOrganizationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolesForOrganization", ctx, organizationID)
	ret0, _ := ret[0].([]db.ListRolesForOrganizationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolesForOrganization indicates an expected call of ListRolesForOrganization.
func (mr *MockQuerierMockRecorder) ListRolesForOrganization(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolesForOrganization", reflect.TypeOf((*MockQuerier)(nil).ListRolesForOrganization), ctx, organizationID)
}

// RemoveUserFromOrganization mocks base method.
func (m *MockQuerier) RemoveUserFromOrganization(ctx context.Context, arg db.RemoveUserFromOrganizationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromOrganization", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromOrganization indicates an expected call of RemoveUserFromOrganization.
func (mr *MockQuerierMockRecorder) RemoveUserFromOrganization(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromOrganization", reflect.TypeOf((*MockQuerier)(nil).RemoveUserFromOrganization), ctx, arg)
}

// RemoveUserRole mocks base method.
func (m *MockQuerier) RemoveUserRole(ctx context.Context, arg db.RemoveUserRoleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserRole", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserRole indicates an expected call of RemoveUserRole.
func (mr *MockQuerierMockRecorder) RemoveUserRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserRole", reflect.TypeOf((*MockQuerier)(nil).RemoveUserRole), ctx, arg)
}

// RevokeApiKey mocks base method.
func (m *MockQuerier) RevokeApiKey(ctx context.Context, arg db.RevokeApiKeyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeApiKey", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeApiKey indicates an expected call of RevokeApiKey.
func (mr *MockQuerierMockRecorder) RevokeApiKey(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeApiKey", reflect.TypeOf((*MockQuerier)(nil).RevokeApiKey), ctx, arg)
}

// RevokeExpiredAPIKeys mocks base method.
func (m *MockQuerier) RevokeExpiredAPIKeys(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeExpiredAPIKeys", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeExpiredAPIKeys indicates an expected call of RevokeExpiredAPIKeys.
func (mr *MockQuerierMockRecorder) RevokeExpiredAPIKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeExpiredAPIKeys", reflect.TypeOf((*MockQuerier)(nil).RevokeExpiredAPIKeys), ctx)
}

// UpdateRole mocks base method.
func (m *MockQuerier) UpdateRole(ctx context.Context, arg db.UpdateRoleParams) (db.UpdateRoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, arg)
	ret0, _ := ret[0].(db.UpdateRoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockQuerierMockRecorder) UpdateRole(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockQuerier)(nil).UpdateRole), ctx, arg)
}

// UpsertUser mocks base method.
func (m *MockQuerier) UpsertUser(ctx context.Context, arg db.UpsertUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockQuerierMockRecorder) UpsertUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockQuerier)(nil).UpsertUser), ctx, arg)
}
