// Code generated by mockery v2. DO NOT EDIT.

package mock

import (
	"context"

	"go.uber.org/mock/gomock"

	db "github.com/arc-self/apps/privacy-service/internal/repository/db"
)

// MockQuerier is a mock of db.Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
}

type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	m := &MockQuerier{ctrl: ctrl}
	m.recorder = &MockQuerierMockRecorder{m}
	return m
}

func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder { return m.recorder }

// ── Cookie Banners ───────────────────────────────────

func (m *MockQuerier) CreateCookieBanner(ctx context.Context, arg db.CreateCookieBannerParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCookieBanner", ctx, arg)
	return ret[0].(db.CookieBanner), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) CreateCookieBanner(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "CreateCookieBanner", ctx, arg)
}

func (m *MockQuerier) GetCookieBanner(ctx context.Context, arg db.GetCookieBannerParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookieBanner", ctx, arg)
	return ret[0].(db.CookieBanner), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) GetCookieBanner(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "GetCookieBanner", ctx, arg)
}

func (m *MockQuerier) GetCookieBannerByDomain(ctx context.Context, arg db.GetCookieBannerByDomainParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookieBannerByDomain", ctx, arg)
	return ret[0].(db.CookieBanner), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) GetCookieBannerByDomain(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "GetCookieBannerByDomain", ctx, arg)
}

func (m *MockQuerier) ListCookieBanners(ctx context.Context, organizationID interface{}) ([]db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCookieBanners", ctx, organizationID)
	v, _ := ret[0].([]db.CookieBanner)
	return v, toErr(ret[1])
}
func (r *MockQuerierMockRecorder) ListCookieBanners(ctx, org interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "ListCookieBanners", ctx, org)
}

func (m *MockQuerier) UpdateCookieBanner(ctx context.Context, arg db.UpdateCookieBannerParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCookieBanner", ctx, arg)
	return ret[0].(db.CookieBanner), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) UpdateCookieBanner(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "UpdateCookieBanner", ctx, arg)
}

func (m *MockQuerier) DeleteCookieBanner(ctx context.Context, arg db.DeleteCookieBannerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCookieBanner", ctx, arg)
	return toErr(ret[0])
}
func (r *MockQuerierMockRecorder) DeleteCookieBanner(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "DeleteCookieBanner", ctx, arg)
}

// ── Purposes ─────────────────────────────────────────

func (m *MockQuerier) CreatePurpose(ctx context.Context, arg db.CreatePurposeParams) (db.Purpose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurpose", ctx, arg)
	return ret[0].(db.Purpose), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) CreatePurpose(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "CreatePurpose", ctx, arg)
}

func (m *MockQuerier) GetPurpose(ctx context.Context, arg db.GetPurposeParams) (db.Purpose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurpose", ctx, arg)
	return ret[0].(db.Purpose), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) GetPurpose(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "GetPurpose", ctx, arg)
}

func (m *MockQuerier) ListPurposes(ctx context.Context, organizationID interface{}) ([]db.Purpose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurposes", ctx, organizationID)
	v, _ := ret[0].([]db.Purpose)
	return v, toErr(ret[1])
}
func (r *MockQuerierMockRecorder) ListPurposes(ctx, org interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "ListPurposes", ctx, org)
}

func (m *MockQuerier) UpdatePurpose(ctx context.Context, arg db.UpdatePurposeParams) (db.Purpose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePurpose", ctx, arg)
	return ret[0].(db.Purpose), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) UpdatePurpose(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "UpdatePurpose", ctx, arg)
}

// ── Consent Forms ─────────────────────────────────────

func (m *MockQuerier) CreateConsentForm(ctx context.Context, arg db.CreateConsentFormParams) (db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConsentForm", ctx, arg)
	return ret[0].(db.ConsentForm), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) CreateConsentForm(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "CreateConsentForm", ctx, arg)
}

func (m *MockQuerier) GetConsentForm(ctx context.Context, arg db.GetConsentFormParams) (db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentForm", ctx, arg)
	return ret[0].(db.ConsentForm), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) GetConsentForm(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "GetConsentForm", ctx, arg)
}

func (m *MockQuerier) ListConsentForms(ctx context.Context, organizationID interface{}) ([]db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConsentForms", ctx, organizationID)
	v, _ := ret[0].([]db.ConsentForm)
	return v, toErr(ret[1])
}
func (r *MockQuerierMockRecorder) ListConsentForms(ctx, org interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "ListConsentForms", ctx, org)
}

func (m *MockQuerier) UpdateConsentForm(ctx context.Context, arg db.UpdateConsentFormParams) (db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConsentForm", ctx, arg)
	return ret[0].(db.ConsentForm), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) UpdateConsentForm(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "UpdateConsentForm", ctx, arg)
}

// ── DPIAs ─────────────────────────────────────────────

func (m *MockQuerier) CreateDPIA(ctx context.Context, arg db.CreateDPIAParams) (db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDPIA", ctx, arg)
	return ret[0].(db.Dpia), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) CreateDPIA(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "CreateDPIA", ctx, arg)
}

func (m *MockQuerier) GetDPIA(ctx context.Context, arg db.GetDPIAParams) (db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDPIA", ctx, arg)
	return ret[0].(db.Dpia), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) GetDPIA(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "GetDPIA", ctx, arg)
}

func (m *MockQuerier) ListDPIAs(ctx context.Context, organizationID interface{}) ([]db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDPIAs", ctx, organizationID)
	v, _ := ret[0].([]db.Dpia)
	return v, toErr(ret[1])
}
func (r *MockQuerierMockRecorder) ListDPIAs(ctx, org interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "ListDPIAs", ctx, org)
}

func (m *MockQuerier) UpdateDPIA(ctx context.Context, arg db.UpdateDPIAParams) (db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDPIA", ctx, arg)
	return ret[0].(db.Dpia), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) UpdateDPIA(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "UpdateDPIA", ctx, arg)
}

// ── ROPAs ─────────────────────────────────────────────

func (m *MockQuerier) CreateROPA(ctx context.Context, arg db.CreateROPAParams) (db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateROPA", ctx, arg)
	return ret[0].(db.Ropa), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) CreateROPA(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "CreateROPA", ctx, arg)
}

func (m *MockQuerier) GetROPA(ctx context.Context, arg db.GetROPAParams) (db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetROPA", ctx, arg)
	return ret[0].(db.Ropa), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) GetROPA(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "GetROPA", ctx, arg)
}

func (m *MockQuerier) ListROPAs(ctx context.Context, organizationID interface{}) ([]db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListROPAs", ctx, organizationID)
	v, _ := ret[0].([]db.Ropa)
	return v, toErr(ret[1])
}
func (r *MockQuerierMockRecorder) ListROPAs(ctx, org interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "ListROPAs", ctx, org)
}

func (m *MockQuerier) UpdateROPA(ctx context.Context, arg db.UpdateROPAParams) (db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateROPA", ctx, arg)
	return ret[0].(db.Ropa), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) UpdateROPA(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "UpdateROPA", ctx, arg)
}

// ── Privacy Requests ──────────────────────────────────

func (m *MockQuerier) CreatePrivacyRequest(ctx context.Context, arg db.CreatePrivacyRequestParams) (db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivacyRequest", ctx, arg)
	return ret[0].(db.PrivacyRequest), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) CreatePrivacyRequest(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "CreatePrivacyRequest", ctx, arg)
}

func (m *MockQuerier) GetPrivacyRequest(ctx context.Context, arg db.GetPrivacyRequestParams) (db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivacyRequest", ctx, arg)
	return ret[0].(db.PrivacyRequest), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) GetPrivacyRequest(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "GetPrivacyRequest", ctx, arg)
}

func (m *MockQuerier) ListPrivacyRequests(ctx context.Context, organizationID interface{}) ([]db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrivacyRequests", ctx, organizationID)
	v, _ := ret[0].([]db.PrivacyRequest)
	return v, toErr(ret[1])
}
func (r *MockQuerierMockRecorder) ListPrivacyRequests(ctx, org interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "ListPrivacyRequests", ctx, org)
}

func (m *MockQuerier) UpdatePrivacyRequest(ctx context.Context, arg db.UpdatePrivacyRequestParams) (db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrivacyRequest", ctx, arg)
	return ret[0].(db.PrivacyRequest), toErr(ret[1])
}
func (r *MockQuerierMockRecorder) UpdatePrivacyRequest(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "UpdatePrivacyRequest", ctx, arg)
}

// ── Outbox ────────────────────────────────────────────

func (m *MockQuerier) InsertOutboxEvent(ctx context.Context, arg db.InsertOutboxEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOutboxEvent", ctx, arg)
	return toErr(ret[0])
}
func (r *MockQuerierMockRecorder) InsertOutboxEvent(ctx, arg interface{}) *gomock.Call {
	return r.mock.ctrl.RecordCall(r.mock, "InsertOutboxEvent", ctx, arg)
}

// ── helpers ───────────────────────────────────────────

func toErr(v interface{}) error {
	if v == nil {
		return nil
	}
	return v.(error)
}
