// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock

import (
	context "context"

	db "github.com/arc-self/apps/privacy-service/internal/repository/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// CreateAuditLog provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateAuditLog(ctx context.Context, arg db.CreateAuditLogParams) (db.AuditLog, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 db.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAuditLogParams) (db.AuditLog, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateAuditLogParams) db.AuditLog); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.AuditLog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateAuditLogParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateBreach provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateBreach(ctx context.Context, arg db.CreateBreachParams) (db.Breach, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBreach")
	}

	var r0 db.Breach
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateBreachParams) (db.Breach, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateBreachParams) db.Breach); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Breach)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateBreachParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateConsentForm provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateConsentForm(ctx context.Context, arg db.CreateConsentFormParams) (db.ConsentForm, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateConsentForm")
	}

	var r0 db.ConsentForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateConsentFormParams) (db.ConsentForm, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateConsentFormParams) db.ConsentForm); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ConsentForm)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateConsentFormParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCookieBanner provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateCookieBanner(ctx context.Context, arg db.CreateCookieBannerParams) (db.CookieBanner, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateCookieBanner")
	}

	var r0 db.CookieBanner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateCookieBannerParams) (db.CookieBanner, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateCookieBannerParams) db.CookieBanner); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.CookieBanner)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateCookieBannerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateDPIA provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateDPIA(ctx context.Context, arg db.CreateDPIAParams) (db.Dpia, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateDPIA")
	}

	var r0 db.Dpia
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateDPIAParams) (db.Dpia, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateDPIAParams) db.Dpia); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Dpia)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateDPIAParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateGrievance provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateGrievance(ctx context.Context, arg db.CreateGrievanceParams) (db.Grievance, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateGrievance")
	}

	var r0 db.Grievance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateGrievanceParams) (db.Grievance, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateGrievanceParams) db.Grievance); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Grievance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateGrievanceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePrivacyRequest provides a mock function with given fields: ctx, arg
func (_m *Querier) CreatePrivacyRequest(ctx context.Context, arg db.CreatePrivacyRequestParams) (db.PrivacyRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrivacyRequest")
	}

	var r0 db.PrivacyRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreatePrivacyRequestParams) (db.PrivacyRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreatePrivacyRequestParams) db.PrivacyRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.PrivacyRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreatePrivacyRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePurpose provides a mock function with given fields: ctx, arg
func (_m *Querier) CreatePurpose(ctx context.Context, arg db.CreatePurposeParams) (db.Purpose, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurpose")
	}

	var r0 db.Purpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreatePurposeParams) (db.Purpose, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreatePurposeParams) db.Purpose); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Purpose)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreatePurposeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateROPA provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateROPA(ctx context.Context, arg db.CreateROPAParams) (db.Ropa, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateROPA")
	}

	var r0 db.Ropa
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateROPAParams) (db.Ropa, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateROPAParams) db.Ropa); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ropa)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateROPAParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateScriptRule provides a mock function with given fields: ctx, arg
func (_m *Querier) CreateScriptRule(ctx context.Context, arg db.CreateScriptRuleParams) (db.ScriptRule, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateScriptRule")
	}

	var r0 db.ScriptRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateScriptRuleParams) (db.ScriptRule, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateScriptRuleParams) db.ScriptRule); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ScriptRule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateScriptRuleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBreach provides a mock function with given fields: ctx, arg
func (_m *Querier) DeleteBreach(ctx context.Context, arg db.DeleteBreachParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBreach")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.DeleteBreachParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCookieBanner provides a mock function with given fields: ctx, arg
func (_m *Querier) DeleteCookieBanner(ctx context.Context, arg db.DeleteCookieBannerParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCookieBanner")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.DeleteCookieBannerParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteScriptRule provides a mock function with given fields: ctx, arg
func (_m *Querier) DeleteScriptRule(ctx context.Context, arg db.DeleteScriptRuleParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScriptRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.DeleteScriptRuleParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBreachByID provides a mock function with given fields: ctx, arg
func (_m *Querier) GetBreachByID(ctx context.Context, arg db.GetBreachByIDParams) (db.Breach, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetBreachByID")
	}

	var r0 db.Breach
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetBreachByIDParams) (db.Breach, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetBreachByIDParams) db.Breach); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Breach)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetBreachByIDParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConsentForm provides a mock function with given fields: ctx, arg
func (_m *Querier) GetConsentForm(ctx context.Context, arg db.GetConsentFormParams) (db.ConsentForm, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetConsentForm")
	}

	var r0 db.ConsentForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetConsentFormParams) (db.ConsentForm, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetConsentFormParams) db.ConsentForm); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ConsentForm)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetConsentFormParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCookieBanner provides a mock function with given fields: ctx, arg
func (_m *Querier) GetCookieBanner(ctx context.Context, arg db.GetCookieBannerParams) (db.CookieBanner, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetCookieBanner")
	}

	var r0 db.CookieBanner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetCookieBannerParams) (db.CookieBanner, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetCookieBannerParams) db.CookieBanner); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.CookieBanner)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetCookieBannerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCookieBannerByDomain provides a mock function with given fields: ctx, arg
func (_m *Querier) GetCookieBannerByDomain(ctx context.Context, arg db.GetCookieBannerByDomainParams) (db.CookieBanner, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetCookieBannerByDomain")
	}

	var r0 db.CookieBanner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetCookieBannerByDomainParams) (db.CookieBanner, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetCookieBannerByDomainParams) db.CookieBanner); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.CookieBanner)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetCookieBannerByDomainParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDPIA provides a mock function with given fields: ctx, arg
func (_m *Querier) GetDPIA(ctx context.Context, arg db.GetDPIAParams) (db.Dpia, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetDPIA")
	}

	var r0 db.Dpia
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetDPIAParams) (db.Dpia, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetDPIAParams) db.Dpia); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Dpia)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetDPIAParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGrievance provides a mock function with given fields: ctx, arg
func (_m *Querier) GetGrievance(ctx context.Context, arg db.GetGrievanceParams) (db.Grievance, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetGrievance")
	}

	var r0 db.Grievance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetGrievanceParams) (db.Grievance, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetGrievanceParams) db.Grievance); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Grievance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetGrievanceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrivacyRequest provides a mock function with given fields: ctx, arg
func (_m *Querier) GetPrivacyRequest(ctx context.Context, arg db.GetPrivacyRequestParams) (db.PrivacyRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivacyRequest")
	}

	var r0 db.PrivacyRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetPrivacyRequestParams) (db.PrivacyRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetPrivacyRequestParams) db.PrivacyRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.PrivacyRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetPrivacyRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPurpose provides a mock function with given fields: ctx, arg
func (_m *Querier) GetPurpose(ctx context.Context, arg db.GetPurposeParams) (db.Purpose, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetPurpose")
	}

	var r0 db.Purpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetPurposeParams) (db.Purpose, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetPurposeParams) db.Purpose); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Purpose)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetPurposeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetROPA provides a mock function with given fields: ctx, arg
func (_m *Querier) GetROPA(ctx context.Context, arg db.GetROPAParams) (db.Ropa, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetROPA")
	}

	var r0 db.Ropa
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetROPAParams) (db.Ropa, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetROPAParams) db.Ropa); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ropa)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetROPAParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetScriptRule provides a mock function with given fields: ctx, arg
func (_m *Querier) GetScriptRule(ctx context.Context, arg db.GetScriptRuleParams) (db.ScriptRule, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetScriptRule")
	}

	var r0 db.ScriptRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetScriptRuleParams) (db.ScriptRule, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetScriptRuleParams) db.ScriptRule); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ScriptRule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetScriptRuleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertCookieConsent provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertCookieConsent(ctx context.Context, arg db.InsertCookieConsentParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertCookieConsent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.InsertCookieConsentParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertOutboxEvent provides a mock function with given fields: ctx, arg
func (_m *Querier) InsertOutboxEvent(ctx context.Context, arg db.InsertOutboxEventParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertOutboxEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.InsertOutboxEventParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListAuditLogs provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListAuditLogs(ctx context.Context, organizationID pgtype.UUID) ([]db.AuditLog, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditLogs")
	}

	var r0 []db.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.AuditLog, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.AuditLog); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListBreaches provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListBreaches(ctx context.Context, organizationID pgtype.UUID) ([]db.Breach, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListBreaches")
	}

	var r0 []db.Breach
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.Breach, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.Breach); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Breach)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListConsentForms provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListConsentForms(ctx context.Context, organizationID pgtype.UUID) ([]db.ConsentForm, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListConsentForms")
	}

	var r0 []db.ConsentForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.ConsentForm, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.ConsentForm); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ConsentForm)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCookieBanners provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListCookieBanners(ctx context.Context, organizationID pgtype.UUID) ([]db.CookieBanner, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListCookieBanners")
	}

	var r0 []db.CookieBanner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.CookieBanner, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.CookieBanner); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.CookieBanner)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDPIAs provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListDPIAs(ctx context.Context, organizationID pgtype.UUID) ([]db.Dpia, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListDPIAs")
	}

	var r0 []db.Dpia
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.Dpia, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.Dpia); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Dpia)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListGrievances provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListGrievances(ctx context.Context, organizationID pgtype.UUID) ([]db.Grievance, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListGrievances")
	}

	var r0 []db.Grievance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.Grievance, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.Grievance); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Grievance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPrivacyRequests provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListPrivacyRequests(ctx context.Context, organizationID pgtype.UUID) ([]db.PrivacyRequest, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListPrivacyRequests")
	}

	var r0 []db.PrivacyRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.PrivacyRequest, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.PrivacyRequest); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.PrivacyRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPurposes provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListPurposes(ctx context.Context, organizationID pgtype.UUID) ([]db.Purpose, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListPurposes")
	}

	var r0 []db.Purpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.Purpose, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.Purpose); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Purpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListROPAs provides a mock function with given fields: ctx, organizationID
func (_m *Querier) ListROPAs(ctx context.Context, organizationID pgtype.UUID) ([]db.Ropa, error) {
	ret := _m.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListROPAs")
	}

	var r0 []db.Ropa
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.Ropa, error)); ok {
		return rf(ctx, organizationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.Ropa); ok {
		r0 = rf(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Ropa)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListScriptRules provides a mock function with given fields: ctx, tenantID
func (_m *Querier) ListScriptRules(ctx context.Context, tenantID pgtype.UUID) ([]db.ScriptRule, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for ListScriptRules")
	}

	var r0 []db.ScriptRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) ([]db.ScriptRule, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgtype.UUID) []db.ScriptRule); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ScriptRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBreach provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateBreach(ctx context.Context, arg db.UpdateBreachParams) (db.Breach, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBreach")
	}

	var r0 db.Breach
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateBreachParams) (db.Breach, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateBreachParams) db.Breach); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Breach)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateBreachParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateConsentForm provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateConsentForm(ctx context.Context, arg db.UpdateConsentFormParams) (db.ConsentForm, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConsentForm")
	}

	var r0 db.ConsentForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateConsentFormParams) (db.ConsentForm, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateConsentFormParams) db.ConsentForm); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ConsentForm)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateConsentFormParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCookieBanner provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateCookieBanner(ctx context.Context, arg db.UpdateCookieBannerParams) (db.CookieBanner, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCookieBanner")
	}

	var r0 db.CookieBanner
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateCookieBannerParams) (db.CookieBanner, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateCookieBannerParams) db.CookieBanner); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.CookieBanner)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateCookieBannerParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDPIA provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateDPIA(ctx context.Context, arg db.UpdateDPIAParams) (db.Dpia, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDPIA")
	}

	var r0 db.Dpia
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateDPIAParams) (db.Dpia, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateDPIAParams) db.Dpia); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Dpia)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateDPIAParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateGrievance provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateGrievance(ctx context.Context, arg db.UpdateGrievanceParams) (db.Grievance, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGrievance")
	}

	var r0 db.Grievance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateGrievanceParams) (db.Grievance, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateGrievanceParams) db.Grievance); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Grievance)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateGrievanceParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePrivacyRequest provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdatePrivacyRequest(ctx context.Context, arg db.UpdatePrivacyRequestParams) (db.PrivacyRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrivacyRequest")
	}

	var r0 db.PrivacyRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdatePrivacyRequestParams) (db.PrivacyRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdatePrivacyRequestParams) db.PrivacyRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.PrivacyRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdatePrivacyRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePurpose provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdatePurpose(ctx context.Context, arg db.UpdatePurposeParams) (db.Purpose, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePurpose")
	}

	var r0 db.Purpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdatePurposeParams) (db.Purpose, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdatePurposeParams) db.Purpose); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Purpose)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdatePurposeParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateROPA provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateROPA(ctx context.Context, arg db.UpdateROPAParams) (db.Ropa, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateROPA")
	}

	var r0 db.Ropa
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateROPAParams) (db.Ropa, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateROPAParams) db.Ropa); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ropa)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateROPAParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateScriptRule provides a mock function with given fields: ctx, arg
func (_m *Querier) UpdateScriptRule(ctx context.Context, arg db.UpdateScriptRuleParams) (db.ScriptRule, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateScriptRule")
	}

	var r0 db.ScriptRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateScriptRuleParams) (db.ScriptRule, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateScriptRuleParams) db.ScriptRule); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.ScriptRule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateScriptRuleParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
