// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/db/querier.go -destination=internal/repository/mock/querier_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	db "github.com/arc-self/apps/privacy-service/internal/repository/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateAuditLog mocks base method.
func (m *MockQuerier) CreateAuditLog(ctx context.Context, arg db.CreateAuditLogParams) (db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuditLog", ctx, arg)
	ret0, _ := ret[0].(db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuditLog indicates an expected call of CreateAuditLog.
func (mr *MockQuerierMockRecorder) CreateAuditLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuditLog", reflect.TypeOf((*MockQuerier)(nil).CreateAuditLog), ctx, arg)
}

// CreateBreach mocks base method.
func (m *MockQuerier) CreateBreach(ctx context.Context, arg db.CreateBreachParams) (db.Breach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBreach", ctx, arg)
	ret0, _ := ret[0].(db.Breach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBreach indicates an expected call of CreateBreach.
func (mr *MockQuerierMockRecorder) CreateBreach(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBreach", reflect.TypeOf((*MockQuerier)(nil).CreateBreach), ctx, arg)
}

// CreateConsentForm mocks base method.
func (m *MockQuerier) CreateConsentForm(ctx context.Context, arg db.CreateConsentFormParams) (db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConsentForm", ctx, arg)
	ret0, _ := ret[0].(db.ConsentForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConsentForm indicates an expected call of CreateConsentForm.
func (mr *MockQuerierMockRecorder) CreateConsentForm(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConsentForm", reflect.TypeOf((*MockQuerier)(nil).CreateConsentForm), ctx, arg)
}

// CreateCookieBanner mocks base method.
func (m *MockQuerier) CreateCookieBanner(ctx context.Context, arg db.CreateCookieBannerParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCookieBanner", ctx, arg)
	ret0, _ := ret[0].(db.CookieBanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCookieBanner indicates an expected call of CreateCookieBanner.
func (mr *MockQuerierMockRecorder) CreateCookieBanner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCookieBanner", reflect.TypeOf((*MockQuerier)(nil).CreateCookieBanner), ctx, arg)
}

// CreateDPIA mocks base method.
func (m *MockQuerier) CreateDPIA(ctx context.Context, arg db.CreateDPIAParams) (db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDPIA", ctx, arg)
	ret0, _ := ret[0].(db.Dpia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDPIA indicates an expected call of CreateDPIA.
func (mr *MockQuerierMockRecorder) CreateDPIA(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDPIA", reflect.TypeOf((*MockQuerier)(nil).CreateDPIA), ctx, arg)
}

// CreateGrievance mocks base method.
func (m *MockQuerier) CreateGrievance(ctx context.Context, arg db.CreateGrievanceParams) (db.Grievance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGrievance", ctx, arg)
	ret0, _ := ret[0].(db.Grievance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGrievance indicates an expected call of CreateGrievance.
func (mr *MockQuerierMockRecorder) CreateGrievance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGrievance", reflect.TypeOf((*MockQuerier)(nil).CreateGrievance), ctx, arg)
}

// CreateMagicToken mocks base method.
func (m *MockQuerier) CreateMagicToken(ctx context.Context, arg db.CreateMagicTokenParams) (db.MagicToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMagicToken", ctx, arg)
	ret0, _ := ret[0].(db.MagicToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMagicToken indicates an expected call of CreateMagicToken.
func (mr *MockQuerierMockRecorder) CreateMagicToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMagicToken", reflect.TypeOf((*MockQuerier)(nil).CreateMagicToken), ctx, arg)
}

// CreateNominee mocks base method.
func (m *MockQuerier) CreateNominee(ctx context.Context, arg db.CreateNomineeParams) (db.Nominee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNominee", ctx, arg)
	ret0, _ := ret[0].(db.Nominee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNominee indicates an expected call of CreateNominee.
func (mr *MockQuerierMockRecorder) CreateNominee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNominee", reflect.TypeOf((*MockQuerier)(nil).CreateNominee), ctx, arg)
}

// CreatePrivacyRequest mocks base method.
func (m *MockQuerier) CreatePrivacyRequest(ctx context.Context, arg db.CreatePrivacyRequestParams) (db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivacyRequest", ctx, arg)
	ret0, _ := ret[0].(db.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivacyRequest indicates an expected call of CreatePrivacyRequest.
func (mr *MockQuerierMockRecorder) CreatePrivacyRequest(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivacyRequest", reflect.TypeOf((*MockQuerier)(nil).CreatePrivacyRequest), ctx, arg)
}

// CreatePurpose mocks base method.
func (m *MockQuerier) CreatePurpose(ctx context.Context, arg db.CreatePurposeParams) (db.CreatePurposeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurpose", ctx, arg)
	ret0, _ := ret[0].(db.CreatePurposeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurpose indicates an expected call of CreatePurpose.
func (mr *MockQuerierMockRecorder) CreatePurpose(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurpose", reflect.TypeOf((*MockQuerier)(nil).CreatePurpose), ctx, arg)
}

// CreateROPA mocks base method.
func (m *MockQuerier) CreateROPA(ctx context.Context, arg db.CreateROPAParams) (db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateROPA", ctx, arg)
	ret0, _ := ret[0].(db.Ropa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateROPA indicates an expected call of CreateROPA.
func (mr *MockQuerierMockRecorder) CreateROPA(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateROPA", reflect.TypeOf((*MockQuerier)(nil).CreateROPA), ctx, arg)
}

// CreateScriptRule mocks base method.
func (m *MockQuerier) CreateScriptRule(ctx context.Context, arg db.CreateScriptRuleParams) (db.ScriptRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScriptRule", ctx, arg)
	ret0, _ := ret[0].(db.ScriptRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScriptRule indicates an expected call of CreateScriptRule.
func (mr *MockQuerierMockRecorder) CreateScriptRule(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScriptRule", reflect.TypeOf((*MockQuerier)(nil).CreateScriptRule), ctx, arg)
}

// DeleteBreach mocks base method.
func (m *MockQuerier) DeleteBreach(ctx context.Context, arg db.DeleteBreachParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBreach", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBreach indicates an expected call of DeleteBreach.
func (mr *MockQuerierMockRecorder) DeleteBreach(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBreach", reflect.TypeOf((*MockQuerier)(nil).DeleteBreach), ctx, arg)
}

// DeleteCookieBanner mocks base method.
func (m *MockQuerier) DeleteCookieBanner(ctx context.Context, arg db.DeleteCookieBannerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCookieBanner", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCookieBanner indicates an expected call of DeleteCookieBanner.
func (mr *MockQuerierMockRecorder) DeleteCookieBanner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCookieBanner", reflect.TypeOf((*MockQuerier)(nil).DeleteCookieBanner), ctx, arg)
}

// DeleteScriptRule mocks base method.
func (m *MockQuerier) DeleteScriptRule(ctx context.Context, arg db.DeleteScriptRuleParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScriptRule", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScriptRule indicates an expected call of DeleteScriptRule.
func (mr *MockQuerierMockRecorder) DeleteScriptRule(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScriptRule", reflect.TypeOf((*MockQuerier)(nil).DeleteScriptRule), ctx, arg)
}

// GetBreachByID mocks base method.
func (m *MockQuerier) GetBreachByID(ctx context.Context, arg db.GetBreachByIDParams) (db.Breach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBreachByID", ctx, arg)
	ret0, _ := ret[0].(db.Breach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBreachByID indicates an expected call of GetBreachByID.
func (mr *MockQuerierMockRecorder) GetBreachByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBreachByID", reflect.TypeOf((*MockQuerier)(nil).GetBreachByID), ctx, arg)
}

// GetConsentForm mocks base method.
func (m *MockQuerier) GetConsentForm(ctx context.Context, arg db.GetConsentFormParams) (db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsentForm", ctx, arg)
	ret0, _ := ret[0].(db.ConsentForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConsentForm indicates an expected call of GetConsentForm.
func (mr *MockQuerierMockRecorder) GetConsentForm(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsentForm", reflect.TypeOf((*MockQuerier)(nil).GetConsentForm), ctx, arg)
}

// GetCookieBanner mocks base method.
func (m *MockQuerier) GetCookieBanner(ctx context.Context, arg db.GetCookieBannerParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookieBanner", ctx, arg)
	ret0, _ := ret[0].(db.CookieBanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCookieBanner indicates an expected call of GetCookieBanner.
func (mr *MockQuerierMockRecorder) GetCookieBanner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCookieBanner", reflect.TypeOf((*MockQuerier)(nil).GetCookieBanner), ctx, arg)
}

// GetCookieBannerByDomain mocks base method.
func (m *MockQuerier) GetCookieBannerByDomain(ctx context.Context, arg db.GetCookieBannerByDomainParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCookieBannerByDomain", ctx, arg)
	ret0, _ := ret[0].(db.CookieBanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCookieBannerByDomain indicates an expected call of GetCookieBannerByDomain.
func (mr *MockQuerierMockRecorder) GetCookieBannerByDomain(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCookieBannerByDomain", reflect.TypeOf((*MockQuerier)(nil).GetCookieBannerByDomain), ctx, arg)
}

// GetDPIA mocks base method.
func (m *MockQuerier) GetDPIA(ctx context.Context, arg db.GetDPIAParams) (db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDPIA", ctx, arg)
	ret0, _ := ret[0].(db.Dpia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDPIA indicates an expected call of GetDPIA.
func (mr *MockQuerierMockRecorder) GetDPIA(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDPIA", reflect.TypeOf((*MockQuerier)(nil).GetDPIA), ctx, arg)
}

// GetGrievance mocks base method.
func (m *MockQuerier) GetGrievance(ctx context.Context, arg db.GetGrievanceParams) (db.Grievance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrievance", ctx, arg)
	ret0, _ := ret[0].(db.Grievance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGrievance indicates an expected call of GetGrievance.
func (mr *MockQuerierMockRecorder) GetGrievance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrievance", reflect.TypeOf((*MockQuerier)(nil).GetGrievance), ctx, arg)
}

// GetMagicToken mocks base method.
func (m *MockQuerier) GetMagicToken(ctx context.Context, token string) (db.MagicToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMagicToken", ctx, token)
	ret0, _ := ret[0].(db.MagicToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMagicToken indicates an expected call of GetMagicToken.
func (mr *MockQuerierMockRecorder) GetMagicToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMagicToken", reflect.TypeOf((*MockQuerier)(nil).GetMagicToken), ctx, token)
}

// GetPrivacyRequest mocks base method.
func (m *MockQuerier) GetPrivacyRequest(ctx context.Context, arg db.GetPrivacyRequestParams) (db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivacyRequest", ctx, arg)
	ret0, _ := ret[0].(db.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivacyRequest indicates an expected call of GetPrivacyRequest.
func (mr *MockQuerierMockRecorder) GetPrivacyRequest(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivacyRequest", reflect.TypeOf((*MockQuerier)(nil).GetPrivacyRequest), ctx, arg)
}

// GetPurpose mocks base method.
func (m *MockQuerier) GetPurpose(ctx context.Context, arg db.GetPurposeParams) (db.GetPurposeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurpose", ctx, arg)
	ret0, _ := ret[0].(db.GetPurposeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurpose indicates an expected call of GetPurpose.
func (mr *MockQuerierMockRecorder) GetPurpose(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurpose", reflect.TypeOf((*MockQuerier)(nil).GetPurpose), ctx, arg)
}

// GetROPA mocks base method.
func (m *MockQuerier) GetROPA(ctx context.Context, arg db.GetROPAParams) (db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetROPA", ctx, arg)
	ret0, _ := ret[0].(db.Ropa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetROPA indicates an expected call of GetROPA.
func (mr *MockQuerierMockRecorder) GetROPA(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetROPA", reflect.TypeOf((*MockQuerier)(nil).GetROPA), ctx, arg)
}

// GetScriptRule mocks base method.
func (m *MockQuerier) GetScriptRule(ctx context.Context, arg db.GetScriptRuleParams) (db.ScriptRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScriptRule", ctx, arg)
	ret0, _ := ret[0].(db.ScriptRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScriptRule indicates an expected call of GetScriptRule.
func (mr *MockQuerierMockRecorder) GetScriptRule(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScriptRule", reflect.TypeOf((*MockQuerier)(nil).GetScriptRule), ctx, arg)
}

// GetUserNominees mocks base method.
func (m *MockQuerier) GetUserNominees(ctx context.Context, userEmail string) ([]db.Nominee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserNominees", ctx, userEmail)
	ret0, _ := ret[0].([]db.Nominee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserNominees indicates an expected call of GetUserNominees.
func (mr *MockQuerierMockRecorder) GetUserNominees(ctx, userEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserNominees", reflect.TypeOf((*MockQuerier)(nil).GetUserNominees), ctx, userEmail)
}

// InsertCookieConsent mocks base method.
func (m *MockQuerier) InsertCookieConsent(ctx context.Context, arg db.InsertCookieConsentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCookieConsent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertCookieConsent indicates an expected call of InsertCookieConsent.
func (mr *MockQuerierMockRecorder) InsertCookieConsent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCookieConsent", reflect.TypeOf((*MockQuerier)(nil).InsertCookieConsent), ctx, arg)
}

// InsertOutboxEvent mocks base method.
func (m *MockQuerier) InsertOutboxEvent(ctx context.Context, arg db.InsertOutboxEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOutboxEvent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOutboxEvent indicates an expected call of InsertOutboxEvent.
func (mr *MockQuerierMockRecorder) InsertOutboxEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOutboxEvent", reflect.TypeOf((*MockQuerier)(nil).InsertOutboxEvent), ctx, arg)
}

// ListAuditLogs mocks base method.
func (m *MockQuerier) ListAuditLogs(ctx context.Context, organizationID pgtype.UUID) ([]db.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditLogs", ctx, organizationID)
	ret0, _ := ret[0].([]db.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditLogs indicates an expected call of ListAuditLogs.
func (mr *MockQuerierMockRecorder) ListAuditLogs(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditLogs", reflect.TypeOf((*MockQuerier)(nil).ListAuditLogs), ctx, organizationID)
}

// ListBreaches mocks base method.
func (m *MockQuerier) ListBreaches(ctx context.Context, organizationID pgtype.UUID) ([]db.Breach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBreaches", ctx, organizationID)
	ret0, _ := ret[0].([]db.Breach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBreaches indicates an expected call of ListBreaches.
func (mr *MockQuerierMockRecorder) ListBreaches(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBreaches", reflect.TypeOf((*MockQuerier)(nil).ListBreaches), ctx, organizationID)
}

// ListConsentForms mocks base method.
func (m *MockQuerier) ListConsentForms(ctx context.Context, organizationID pgtype.UUID) ([]db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConsentForms", ctx, organizationID)
	ret0, _ := ret[0].([]db.ConsentForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConsentForms indicates an expected call of ListConsentForms.
func (mr *MockQuerierMockRecorder) ListConsentForms(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConsentForms", reflect.TypeOf((*MockQuerier)(nil).ListConsentForms), ctx, organizationID)
}

// ListCookieBanners mocks base method.
func (m *MockQuerier) ListCookieBanners(ctx context.Context, organizationID pgtype.UUID) ([]db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCookieBanners", ctx, organizationID)
	ret0, _ := ret[0].([]db.CookieBanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCookieBanners indicates an expected call of ListCookieBanners.
func (mr *MockQuerierMockRecorder) ListCookieBanners(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCookieBanners", reflect.TypeOf((*MockQuerier)(nil).ListCookieBanners), ctx, organizationID)
}

// ListDPIAs mocks base method.
func (m *MockQuerier) ListDPIAs(ctx context.Context, organizationID pgtype.UUID) ([]db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDPIAs", ctx, organizationID)
	ret0, _ := ret[0].([]db.Dpia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDPIAs indicates an expected call of ListDPIAs.
func (mr *MockQuerierMockRecorder) ListDPIAs(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDPIAs", reflect.TypeOf((*MockQuerier)(nil).ListDPIAs), ctx, organizationID)
}

// ListGrievances mocks base method.
func (m *MockQuerier) ListGrievances(ctx context.Context, organizationID pgtype.UUID) ([]db.Grievance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGrievances", ctx, organizationID)
	ret0, _ := ret[0].([]db.Grievance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGrievances indicates an expected call of ListGrievances.
func (mr *MockQuerierMockRecorder) ListGrievances(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGrievances", reflect.TypeOf((*MockQuerier)(nil).ListGrievances), ctx, organizationID)
}

// ListPrivacyRequests mocks base method.
func (m *MockQuerier) ListPrivacyRequests(ctx context.Context, organizationID pgtype.UUID) ([]db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPrivacyRequests", ctx, organizationID)
	ret0, _ := ret[0].([]db.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrivacyRequests indicates an expected call of ListPrivacyRequests.
func (mr *MockQuerierMockRecorder) ListPrivacyRequests(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrivacyRequests", reflect.TypeOf((*MockQuerier)(nil).ListPrivacyRequests), ctx, organizationID)
}

// ListPurposes mocks base method.
func (m *MockQuerier) ListPurposes(ctx context.Context, organizationID pgtype.UUID) ([]db.ListPurposesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurposes", ctx, organizationID)
	ret0, _ := ret[0].([]db.ListPurposesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurposes indicates an expected call of ListPurposes.
func (mr *MockQuerierMockRecorder) ListPurposes(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurposes", reflect.TypeOf((*MockQuerier)(nil).ListPurposes), ctx, organizationID)
}

// ListROPAs mocks base method.
func (m *MockQuerier) ListROPAs(ctx context.Context, organizationID pgtype.UUID) ([]db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListROPAs", ctx, organizationID)
	ret0, _ := ret[0].([]db.Ropa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListROPAs indicates an expected call of ListROPAs.
func (mr *MockQuerierMockRecorder) ListROPAs(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListROPAs", reflect.TypeOf((*MockQuerier)(nil).ListROPAs), ctx, organizationID)
}

// ListScriptRules mocks base method.
func (m *MockQuerier) ListScriptRules(ctx context.Context, tenantID pgtype.UUID) ([]db.ScriptRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScriptRules", ctx, tenantID)
	ret0, _ := ret[0].([]db.ScriptRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScriptRules indicates an expected call of ListScriptRules.
func (mr *MockQuerierMockRecorder) ListScriptRules(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScriptRules", reflect.TypeOf((*MockQuerier)(nil).ListScriptRules), ctx, tenantID)
}

// ListUserGrievances mocks base method.
func (m *MockQuerier) ListUserGrievances(ctx context.Context, reporterEmail pgtype.Text) ([]db.Grievance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserGrievances", ctx, reporterEmail)
	ret0, _ := ret[0].([]db.Grievance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserGrievances indicates an expected call of ListUserGrievances.
func (mr *MockQuerierMockRecorder) ListUserGrievances(ctx, reporterEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserGrievances", reflect.TypeOf((*MockQuerier)(nil).ListUserGrievances), ctx, reporterEmail)
}

// ListUserPrivacyRequests mocks base method.
func (m *MockQuerier) ListUserPrivacyRequests(ctx context.Context, requesterEmail pgtype.Text) ([]db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserPrivacyRequests", ctx, requesterEmail)
	ret0, _ := ret[0].([]db.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserPrivacyRequests indicates an expected call of ListUserPrivacyRequests.
func (mr *MockQuerierMockRecorder) ListUserPrivacyRequests(ctx, requesterEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserPrivacyRequests", reflect.TypeOf((*MockQuerier)(nil).ListUserPrivacyRequests), ctx, requesterEmail)
}

// MarkMagicTokenUsed mocks base method.
func (m *MockQuerier) MarkMagicTokenUsed(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMagicTokenUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMagicTokenUsed indicates an expected call of MarkMagicTokenUsed.
func (mr *MockQuerierMockRecorder) MarkMagicTokenUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMagicTokenUsed", reflect.TypeOf((*MockQuerier)(nil).MarkMagicTokenUsed), ctx, id)
}

// RecordConsentReceipt mocks base method.
func (m *MockQuerier) RecordConsentReceipt(ctx context.Context, arg db.RecordConsentReceiptParams) (db.ConsentReceipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordConsentReceipt", ctx, arg)
	ret0, _ := ret[0].(db.ConsentReceipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordConsentReceipt indicates an expected call of RecordConsentReceipt.
func (mr *MockQuerierMockRecorder) RecordConsentReceipt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordConsentReceipt", reflect.TypeOf((*MockQuerier)(nil).RecordConsentReceipt), ctx, arg)
}

// UpdateBreach mocks base method.
func (m *MockQuerier) UpdateBreach(ctx context.Context, arg db.UpdateBreachParams) (db.Breach, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBreach", ctx, arg)
	ret0, _ := ret[0].(db.Breach)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBreach indicates an expected call of UpdateBreach.
func (mr *MockQuerierMockRecorder) UpdateBreach(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBreach", reflect.TypeOf((*MockQuerier)(nil).UpdateBreach), ctx, arg)
}

// UpdateConsentForm mocks base method.
func (m *MockQuerier) UpdateConsentForm(ctx context.Context, arg db.UpdateConsentFormParams) (db.ConsentForm, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConsentForm", ctx, arg)
	ret0, _ := ret[0].(db.ConsentForm)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConsentForm indicates an expected call of UpdateConsentForm.
func (mr *MockQuerierMockRecorder) UpdateConsentForm(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConsentForm", reflect.TypeOf((*MockQuerier)(nil).UpdateConsentForm), ctx, arg)
}

// UpdateCookieBanner mocks base method.
func (m *MockQuerier) UpdateCookieBanner(ctx context.Context, arg db.UpdateCookieBannerParams) (db.CookieBanner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCookieBanner", ctx, arg)
	ret0, _ := ret[0].(db.CookieBanner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCookieBanner indicates an expected call of UpdateCookieBanner.
func (mr *MockQuerierMockRecorder) UpdateCookieBanner(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCookieBanner", reflect.TypeOf((*MockQuerier)(nil).UpdateCookieBanner), ctx, arg)
}

// UpdateDPIA mocks base method.
func (m *MockQuerier) UpdateDPIA(ctx context.Context, arg db.UpdateDPIAParams) (db.Dpia, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDPIA", ctx, arg)
	ret0, _ := ret[0].(db.Dpia)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDPIA indicates an expected call of UpdateDPIA.
func (mr *MockQuerierMockRecorder) UpdateDPIA(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDPIA", reflect.TypeOf((*MockQuerier)(nil).UpdateDPIA), ctx, arg)
}

// UpdateGrievance mocks base method.
func (m *MockQuerier) UpdateGrievance(ctx context.Context, arg db.UpdateGrievanceParams) (db.Grievance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGrievance", ctx, arg)
	ret0, _ := ret[0].(db.Grievance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGrievance indicates an expected call of UpdateGrievance.
func (mr *MockQuerierMockRecorder) UpdateGrievance(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGrievance", reflect.TypeOf((*MockQuerier)(nil).UpdateGrievance), ctx, arg)
}

// UpdateNomineeStatus mocks base method.
func (m *MockQuerier) UpdateNomineeStatus(ctx context.Context, arg db.UpdateNomineeStatusParams) (db.Nominee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNomineeStatus", ctx, arg)
	ret0, _ := ret[0].(db.Nominee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNomineeStatus indicates an expected call of UpdateNomineeStatus.
func (mr *MockQuerierMockRecorder) UpdateNomineeStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNomineeStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateNomineeStatus), ctx, arg)
}

// UpdatePrivacyRequest mocks base method.
func (m *MockQuerier) UpdatePrivacyRequest(ctx context.Context, arg db.UpdatePrivacyRequestParams) (db.PrivacyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrivacyRequest", ctx, arg)
	ret0, _ := ret[0].(db.PrivacyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePrivacyRequest indicates an expected call of UpdatePrivacyRequest.
func (mr *MockQuerierMockRecorder) UpdatePrivacyRequest(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrivacyRequest", reflect.TypeOf((*MockQuerier)(nil).UpdatePrivacyRequest), ctx, arg)
}

// UpdatePurpose mocks base method.
func (m *MockQuerier) UpdatePurpose(ctx context.Context, arg db.UpdatePurposeParams) (db.UpdatePurposeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePurpose", ctx, arg)
	ret0, _ := ret[0].(db.UpdatePurposeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePurpose indicates an expected call of UpdatePurpose.
func (mr *MockQuerierMockRecorder) UpdatePurpose(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePurpose", reflect.TypeOf((*MockQuerier)(nil).UpdatePurpose), ctx, arg)
}

// UpdateROPA mocks base method.
func (m *MockQuerier) UpdateROPA(ctx context.Context, arg db.UpdateROPAParams) (db.Ropa, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateROPA", ctx, arg)
	ret0, _ := ret[0].(db.Ropa)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateROPA indicates an expected call of UpdateROPA.
func (mr *MockQuerierMockRecorder) UpdateROPA(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateROPA", reflect.TypeOf((*MockQuerier)(nil).UpdateROPA), ctx, arg)
}

// UpdateScriptRule mocks base method.
func (m *MockQuerier) UpdateScriptRule(ctx context.Context, arg db.UpdateScriptRuleParams) (db.ScriptRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScriptRule", ctx, arg)
	ret0, _ := ret[0].(db.ScriptRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScriptRule indicates an expected call of UpdateScriptRule.
func (mr *MockQuerierMockRecorder) UpdateScriptRule(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScriptRule", reflect.TypeOf((*MockQuerier)(nil).UpdateScriptRule), ctx, arg)
}
