// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: packages/go-core/proto/iam/v1/iam.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateAccessRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PermissionSlug string                 `protobuf:"bytes,3,opt,name=permission_slug,json=permissionSlug,proto3" json:"permission_slug,omitempty"` // e.g. "item:read", "iam:manage"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateAccessRequest) Reset() {
	*x = EvaluateAccessRequest{}
	mi := &file_packages_go_core_proto_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAccessRequest) ProtoMessage() {}

func (x *EvaluateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_go_core_proto_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAccessRequest.ProtoReflect.Descriptor instead.
func (*EvaluateAccessRequest) Descriptor() ([]byte, []int) {
	return file_packages_go_core_proto_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluateAccessRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EvaluateAccessRequest) GetPermissionSlug() string {
	if x != nil {
		return x.PermissionSlug
	}
	return ""
}

type EvaluateAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"` // All permission slugs the user holds in this org
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateAccessResponse) Reset() {
	*x = EvaluateAccessResponse{}
	mi := &file_packages_go_core_proto_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAccessResponse) ProtoMessage() {}

func (x *EvaluateAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_go_core_proto_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAccessResponse.ProtoReflect.Descriptor instead.
func (*EvaluateAccessResponse) Descriptor() ([]byte, []int) {
	return file_packages_go_core_proto_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *EvaluateAccessResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_packages_go_core_proto_iam_v1_iam_proto protoreflect.FileDescriptor

const file_packages_go_core_proto_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"'packages/go-core/proto/iam/v1/iam.proto\x12\x06iam.v1\"\x82\x01\n" +
	"\x15EvaluateAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12'\n" +
	"\x0fpermission_slug\x18\x03 \x01(\tR\x0epermissionSlug\"T\n" +
	"\x16EvaluateAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions2]\n" +
	"\n" +
	"IAMService\x12O\n" +
	"\x0eEvaluateAccess\x12\x1d.iam.v1.EvaluateAccessRequest\x1a\x1e.iam.v1.EvaluateAccessResponseB9Z7github.com/arc-self/packages/go-core/proto/iam/v1;iamv1b\x06proto3"

var (
	file_packages_go_core_proto_iam_v1_iam_proto_rawDescOnce sync.Once
	file_packages_go_core_proto_iam_v1_iam_proto_rawDescData []byte
)

func file_packages_go_core_proto_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_packages_go_core_proto_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_packages_go_core_proto_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_go_core_proto_iam_v1_iam_proto_rawDesc), len(file_packages_go_core_proto_iam_v1_iam_proto_rawDesc)))
	})
	return file_packages_go_core_proto_iam_v1_iam_proto_rawDescData
}

var file_packages_go_core_proto_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_packages_go_core_proto_iam_v1_iam_proto_goTypes = []any{
	(*EvaluateAccessRequest)(nil),  // 0: iam.v1.EvaluateAccessRequest
	(*EvaluateAccessResponse)(nil), // 1: iam.v1.EvaluateAccessResponse
}
var file_packages_go_core_proto_iam_v1_iam_proto_depIdxs = []int32{
	0, // 0: iam.v1.IAMService.EvaluateAccess:input_type -> iam.v1.EvaluateAccessRequest
	1, // 1: iam.v1.IAMService.EvaluateAccess:output_type -> iam.v1.EvaluateAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packages_go_core_proto_iam_v1_iam_proto_init() }
func file_packages_go_core_proto_iam_v1_iam_proto_init() {
	if File_packages_go_core_proto_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_go_core_proto_iam_v1_iam_proto_rawDesc), len(file_packages_go_core_proto_iam_v1_iam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_go_core_proto_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_packages_go_core_proto_iam_v1_iam_proto_depIdxs,
		MessageInfos:      file_packages_go_core_proto_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_packages_go_core_proto_iam_v1_iam_proto = out.File
	file_packages_go_core_proto_iam_v1_iam_proto_goTypes = nil
	file_packages_go_core_proto_iam_v1_iam_proto_depIdxs = nil
}
