// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (organization_id, name, key_prefix, key_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, key_prefix, key_hash, created_by, revoked, expires_at, created_at
`

type CreateApiKeyParams struct {
	OrganizationID pgtype.UUID
	Name           string
	KeyPrefix      string
	KeyHash        string
	CreatedBy      pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.OrganizationID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, organization_id, name, key_prefix, created_by, revoked, expires_at, created_at
FROM api_keys
WHERE key_hash = $1 AND revoked = false
`

type GetApiKeyByHashRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	KeyPrefix      string
	CreatedBy      pgtype.UUID
	Revoked        bool
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (GetApiKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i GetApiKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.KeyPrefix,
		&i.CreatedBy,
		&i.Revoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, organization_id, name, key_prefix, created_by, revoked, expires_at, created_at
FROM api_keys
WHERE organization_id = $1 AND revoked = false
ORDER BY created_at DESC
`

type ListApiKeysRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	KeyPrefix      string
	CreatedBy      pgtype.UUID
	Revoked        bool
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListApiKeys(ctx context.Context, organizationID pgtype.UUID) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysRow
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.KeyPrefix,
			&i.CreatedBy,
			&i.Revoked,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :exec
UPDATE api_keys
SET revoked = true
WHERE id = $1 AND organization_id = $2
`

type RevokeApiKeyParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) error {
	_, err := q.db.Exec(ctx, revokeApiKey, arg.ID, arg.OrganizationID)
	return err
}

const revokeExpiredAPIKeys = `-- name: RevokeExpiredAPIKeys :execrows
UPDATE api_keys
SET revoked = true
WHERE revoked = false AND expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) RevokeExpiredAPIKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeExpiredAPIKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
