// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

const revokeExpiredAPIKeys = `UPDATE api_keys SET revoked = true WHERE revoked = false AND expires_at IS NOT NULL AND expires_at < NOW()`

// RevokeExpiredAPIKeys marks all expired, non-revoked API keys as revoked.
// Returns the number of rows affected.
func (q *Queries) RevokeExpiredAPIKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeExpiredAPIKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
