// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Role struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
}

type RolePermission struct {
	RoleID         pgtype.UUID
	PermissionSlug string
}

type User struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

type UserOrganizationRole struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
}
