// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listOrganizationUsers = `-- name: ListOrganizationUsers :many
SELECT
    u.id,
    u.email,
    r.id AS role_id,
    r.name AS role_name,
    u.created_at
FROM user_organization_roles uor
JOIN users u ON uor.user_id = u.id
JOIN roles r ON uor.role_id = r.id
WHERE uor.organization_id = $1
ORDER BY u.email
`

type ListOrganizationUsersRow struct {
	ID        pgtype.UUID
	Email     string
	RoleID    pgtype.UUID
	RoleName  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListOrganizationUsers(ctx context.Context, organizationID pgtype.UUID) ([]ListOrganizationUsersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationUsers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationUsersRow
	for rows.Next() {
		var i ListOrganizationUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.RoleID,
			&i.RoleName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromOrganization = `-- name: RemoveUserFromOrganization :exec
DELETE FROM user_organization_roles
WHERE user_id = $1 AND organization_id = $2
`

type RemoveUserFromOrganizationParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) RemoveUserFromOrganization(ctx context.Context, arg RemoveUserFromOrganizationParams) error {
	_, err := q.db.Exec(ctx, removeUserFromOrganization, arg.UserID, arg.OrganizationID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE user_organization_roles
SET role_id = $3
WHERE user_id = $1 AND organization_id = $2
`

type UpdateUserRoleParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.UserID, arg.OrganizationID, arg.RoleID)
	return err
}
