// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error)
	GetDefaultRole(ctx context.Context, organizationID pgtype.UUID) (Role, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	GetUserPermissionsInOrg(ctx context.Context, arg GetUserPermissionsInOrgParams) ([]string, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
