// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserPermission = `-- name: CheckUserPermission :one
SELECT EXISTS (
    SELECT 1 
    FROM user_organization_roles uor
    JOIN roles r ON uor.role_id = r.id
    JOIN role_permissions rp ON r.id = rp.role_id
    WHERE uor.user_id = $1 
      AND uor.organization_id = $2 
      AND rp.permission_slug = $3
)
`

type CheckUserPermissionParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	PermissionSlug string
}

func (q *Queries) CheckUserPermission(ctx context.Context, arg CheckUserPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserPermission, arg.UserID, arg.OrganizationID, arg.PermissionSlug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserPermissionsInOrg = `-- name: GetUserPermissionsInOrg :many
SELECT DISTINCT rp.permission_slug
FROM user_organization_roles uor
JOIN roles r ON uor.role_id = r.id
JOIN role_permissions rp ON r.id = rp.role_id
WHERE uor.user_id = $1 AND uor.organization_id = $2
`

type GetUserPermissionsInOrgParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetUserPermissionsInOrg(ctx context.Context, arg GetUserPermissionsInOrgParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissionsInOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_slug string
		if err := rows.Scan(&permission_slug); err != nil {
			return nil, err
		}
		items = append(items, permission_slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
