// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT
    o.id   AS organization_id,
    o.name AS organization_name,
    r.name AS role_name
FROM user_organization_roles uor
JOIN organizations o ON uor.organization_id = o.id
JOIN roles r ON uor.role_id = r.id
WHERE uor.user_id = $1
`

type GetUserOrganizationsRow struct {
	OrganizationID   pgtype.UUID
	OrganizationName string
	RoleName         string
}

func (q *Queries) GetUserOrganizations(ctx context.Context, userID pgtype.UUID) ([]GetUserOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, getUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrganizationsRow
	for rows.Next() {
		var i GetUserOrganizationsRow
		if err := rows.Scan(&i.OrganizationID, &i.OrganizationName, &i.RoleName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
