// Code generated by MockGen. DO NOT EDIT.
// Source: apps/abc-service/internal/repository/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=apps/abc-service/internal/repository/db/querier.go -destination=apps/abc-service/internal/repository/mock/querier_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	db "github.com/arc-self/apps/abc-service/internal/repository/db"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockQuerier) CreateCategory(ctx context.Context, arg db.CreateCategoryParams) (db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, arg)
	ret0, _ := ret[0].(db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockQuerierMockRecorder) CreateCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockQuerier)(nil).CreateCategory), ctx, arg)
}

// CreateItem mocks base method.
func (m *MockQuerier) CreateItem(ctx context.Context, arg db.CreateItemParams) (db.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, arg)
	ret0, _ := ret[0].(db.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockQuerierMockRecorder) CreateItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockQuerier)(nil).CreateItem), ctx, arg)
}

// GetItem mocks base method.
func (m *MockQuerier) GetItem(ctx context.Context, arg db.GetItemParams) (db.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, arg)
	ret0, _ := ret[0].(db.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockQuerierMockRecorder) GetItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockQuerier)(nil).GetItem), ctx, arg)
}

// InsertOutboxEvent mocks base method.
func (m *MockQuerier) InsertOutboxEvent(ctx context.Context, arg db.InsertOutboxEventParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOutboxEvent", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOutboxEvent indicates an expected call of InsertOutboxEvent.
func (mr *MockQuerierMockRecorder) InsertOutboxEvent(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOutboxEvent", reflect.TypeOf((*MockQuerier)(nil).InsertOutboxEvent), ctx, arg)
}

// ListCategories mocks base method.
func (m *MockQuerier) ListCategories(ctx context.Context, organizationID pgtype.UUID) ([]db.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, organizationID)
	ret0, _ := ret[0].([]db.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockQuerierMockRecorder) ListCategories(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockQuerier)(nil).ListCategories), ctx, organizationID)
}

// ListItems mocks base method.
func (m *MockQuerier) ListItems(ctx context.Context, organizationID pgtype.UUID) ([]db.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, organizationID)
	ret0, _ := ret[0].([]db.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockQuerierMockRecorder) ListItems(ctx, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockQuerier)(nil).ListItems), ctx, organizationID)
}

// SoftDeleteItem mocks base method.
func (m *MockQuerier) SoftDeleteItem(ctx context.Context, arg db.SoftDeleteItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteItem indicates an expected call of SoftDeleteItem.
func (mr *MockQuerierMockRecorder) SoftDeleteItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteItem", reflect.TypeOf((*MockQuerier)(nil).SoftDeleteItem), ctx, arg)
}

// UpdateItemStatus mocks base method.
func (m *MockQuerier) UpdateItemStatus(ctx context.Context, arg db.UpdateItemStatusParams) (db.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItemStatus", ctx, arg)
	ret0, _ := ret[0].(db.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItemStatus indicates an expected call of UpdateItemStatus.
func (mr *MockQuerierMockRecorder) UpdateItemStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItemStatus", reflect.TypeOf((*MockQuerier)(nil).UpdateItemStatus), ctx, arg)
}
