// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, organization_id, name)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, created_at
`

type CreateCategoryParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.ID, arg.OrganizationID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (id, organization_id, category_id, name, description, status)
VALUES ($1, $2, $3, $4, $5, 'DRAFT')
RETURNING id, name, description, status, created_at, updated_at, category_id, deleted_at, organization_id
`

type CreateItemParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	CategoryID     pgtype.UUID
	Name           string
	Description    pgtype.Text
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.OrganizationID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, name, description, status, created_at, updated_at, category_id, deleted_at, organization_id FROM items
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type GetItemParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, arg.ID, arg.OrganizationID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, organization_id, name, created_at FROM categories
WHERE organization_id = $1
ORDER BY name ASC
`

func (q *Queries) ListCategories(ctx context.Context, organizationID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, name, description, status, created_at, updated_at, category_id, deleted_at, organization_id FROM items
WHERE organization_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListItems(ctx context.Context, organizationID pgtype.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.DeletedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteItem = `-- name: SoftDeleteItem :exec
UPDATE items
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND organization_id = $2 AND deleted_at IS NULL
`

type SoftDeleteItemParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) error {
	_, err := q.db.Exec(ctx, softDeleteItem, arg.ID, arg.OrganizationID)
	return err
}

const updateItemStatus = `-- name: UpdateItemStatus :one
UPDATE items
SET status = $2, updated_at = NOW()
WHERE id = $1 AND organization_id = $3 AND deleted_at IS NULL
RETURNING id, name, description, status, created_at, updated_at, category_id, deleted_at, organization_id
`

type UpdateItemStatusParams struct {
	ID             pgtype.UUID
	Status         string
	OrganizationID pgtype.UUID
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItemStatus, arg.ID, arg.Status, arg.OrganizationID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryID,
		&i.DeletedAt,
		&i.OrganizationID,
	)
	return i, err
}
