// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (id, aggregate_type, aggregate_id, actor_id, type, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOutboxEventParams struct {
	ID            pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	ActorID       pgtype.UUID
	Type          string
	Payload       []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.ActorID,
		arg.Type,
		arg.Payload,
	)
	return err
}
