// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	CreatedAt      pgtype.Timestamptz
}

type Item struct {
	ID             pgtype.UUID
	Name           string
	Description    pgtype.Text
	Status         string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CategoryID     pgtype.UUID
	DeletedAt      pgtype.Timestamptz
	OrganizationID pgtype.UUID
}

type OutboxEvent struct {
	ID            pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	ActorID       pgtype.UUID
	Type          string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
}
