// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	GetItem(ctx context.Context, arg GetItemParams) (Item, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListCategories(ctx context.Context, organizationID pgtype.UUID) ([]Category, error)
	ListItems(ctx context.Context, organizationID pgtype.UUID) ([]Item, error)
	SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) error
	UpdateItemStatus(ctx context.Context, arg UpdateItemStatusParams) (Item, error)
}

var _ Querier = (*Queries)(nil)
