// Code generated by MockGen. DO NOT EDIT.
// Source: apps/audit-service/internal/repository/db/querier.go
//
// Generated by this command:
//
//	mockgen -source=apps/audit-service/internal/repository/db/querier.go -destination=apps/audit-service/internal/repository/mock/querier_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	db "github.com/arc-self/apps/audit-service/internal/repository/db"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// InsertAuditLog mocks base method.
func (m *MockQuerier) InsertAuditLog(ctx context.Context, arg db.InsertAuditLogParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAuditLog", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAuditLog indicates an expected call of InsertAuditLog.
func (mr *MockQuerierMockRecorder) InsertAuditLog(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAuditLog", reflect.TypeOf((*MockQuerier)(nil).InsertAuditLog), ctx, arg)
}
