// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    organization_id, action, actor_email, target_entity, target_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, organization_id, action, actor_email, target_entity, target_id, timestamp
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID
	Action         string
	ActorEmail     pgtype.Text
	TargetEntity   pgtype.Text
	TargetID       pgtype.Text
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrganizationID,
		arg.Action,
		arg.ActorEmail,
		arg.TargetEntity,
		arg.TargetID,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Action,
		&i.ActorEmail,
		&i.TargetEntity,
		&i.TargetID,
		&i.Timestamp,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, organization_id, action, actor_email, target_entity, target_id, timestamp FROM audit_logs
WHERE organization_id = $1
ORDER BY timestamp DESC
`

func (q *Queries) ListAuditLogs(ctx context.Context, organizationID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Action,
			&i.ActorEmail,
			&i.TargetEntity,
			&i.TargetID,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
