// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: breaches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBreach = `-- name: CreateBreach :one
INSERT INTO breaches (
    organization_id, title, severity, status, incident_date, description, remediation_plan
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, organization_id, title, severity, status, incident_date, description, remediation_plan, created_at, updated_at
`

type CreateBreachParams struct {
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	Title           string             `json:"title"`
	Severity        pgtype.Text        `json:"severity"`
	Status          pgtype.Text        `json:"status"`
	IncidentDate    pgtype.Timestamptz `json:"incident_date"`
	Description     pgtype.Text        `json:"description"`
	RemediationPlan pgtype.Text        `json:"remediation_plan"`
}

func (q *Queries) CreateBreach(ctx context.Context, arg CreateBreachParams) (Breach, error) {
	row := q.db.QueryRow(ctx, createBreach,
		arg.OrganizationID,
		arg.Title,
		arg.Severity,
		arg.Status,
		arg.IncidentDate,
		arg.Description,
		arg.RemediationPlan,
	)
	var i Breach
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.IncidentDate,
		&i.Description,
		&i.RemediationPlan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBreach = `-- name: DeleteBreach :exec
DELETE FROM breaches
WHERE id = $1 AND organization_id = $2
`

type DeleteBreachParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteBreach(ctx context.Context, arg DeleteBreachParams) error {
	_, err := q.db.Exec(ctx, deleteBreach, arg.ID, arg.OrganizationID)
	return err
}

const getBreachByID = `-- name: GetBreachByID :one
SELECT id, organization_id, title, severity, status, incident_date, description, remediation_plan, created_at, updated_at FROM breaches
WHERE id = $1 AND organization_id = $2
`

type GetBreachByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetBreachByID(ctx context.Context, arg GetBreachByIDParams) (Breach, error) {
	row := q.db.QueryRow(ctx, getBreachByID, arg.ID, arg.OrganizationID)
	var i Breach
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.IncidentDate,
		&i.Description,
		&i.RemediationPlan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBreaches = `-- name: ListBreaches :many
SELECT id, organization_id, title, severity, status, incident_date, description, remediation_plan, created_at, updated_at FROM breaches
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBreaches(ctx context.Context, organizationID pgtype.UUID) ([]Breach, error) {
	rows, err := q.db.Query(ctx, listBreaches, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Breach
	for rows.Next() {
		var i Breach
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.IncidentDate,
			&i.Description,
			&i.RemediationPlan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBreach = `-- name: UpdateBreach :one
UPDATE breaches
SET
    title = COALESCE($3, title),
    severity = COALESCE($4, severity),
    status = COALESCE($5, status),
    incident_date = COALESCE($6, incident_date),
    description = COALESCE($7, description),
    remediation_plan = COALESCE($8, remediation_plan),
    updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, title, severity, status, incident_date, description, remediation_plan, created_at, updated_at
`

type UpdateBreachParams struct {
	ID              pgtype.UUID        `json:"id"`
	OrganizationID  pgtype.UUID        `json:"organization_id"`
	Title           string             `json:"title"`
	Severity        pgtype.Text        `json:"severity"`
	Status          pgtype.Text        `json:"status"`
	IncidentDate    pgtype.Timestamptz `json:"incident_date"`
	Description     pgtype.Text        `json:"description"`
	RemediationPlan pgtype.Text        `json:"remediation_plan"`
}

func (q *Queries) UpdateBreach(ctx context.Context, arg UpdateBreachParams) (Breach, error) {
	row := q.db.QueryRow(ctx, updateBreach,
		arg.ID,
		arg.OrganizationID,
		arg.Title,
		arg.Severity,
		arg.Status,
		arg.IncidentDate,
		arg.Description,
		arg.RemediationPlan,
	)
	var i Breach
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.IncidentDate,
		&i.Description,
		&i.RemediationPlan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
