// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consent_forms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConsentForm = `-- name: CreateConsentForm :one
INSERT INTO consent_forms (id, organization_id, name, description, active, form_config, purposes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, name, description, active, form_config, purposes, created_at, updated_at
`

type CreateConsentFormParams struct {
	ID             pgtype.UUID   `json:"id"`
	OrganizationID pgtype.UUID   `json:"organization_id"`
	Name           string        `json:"name"`
	Description    pgtype.Text   `json:"description"`
	Active         pgtype.Bool   `json:"active"`
	FormConfig     []byte        `json:"form_config"`
	Purposes       []pgtype.UUID `json:"purposes"`
}

func (q *Queries) CreateConsentForm(ctx context.Context, arg CreateConsentFormParams) (ConsentForm, error) {
	row := q.db.QueryRow(ctx, createConsentForm,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.FormConfig,
		arg.Purposes,
	)
	var i ConsentForm
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.FormConfig,
		&i.Purposes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConsentForm = `-- name: GetConsentForm :one
SELECT id, organization_id, name, description, active, form_config, purposes, created_at, updated_at FROM consent_forms
WHERE id = $1 AND organization_id = $2
`

type GetConsentFormParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetConsentForm(ctx context.Context, arg GetConsentFormParams) (ConsentForm, error) {
	row := q.db.QueryRow(ctx, getConsentForm, arg.ID, arg.OrganizationID)
	var i ConsentForm
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.FormConfig,
		&i.Purposes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConsentForms = `-- name: ListConsentForms :many
SELECT id, organization_id, name, description, active, form_config, purposes, created_at, updated_at FROM consent_forms
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConsentForms(ctx context.Context, organizationID pgtype.UUID) ([]ConsentForm, error) {
	rows, err := q.db.Query(ctx, listConsentForms, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentForm
	for rows.Next() {
		var i ConsentForm
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.FormConfig,
			&i.Purposes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsentForm = `-- name: UpdateConsentForm :one
UPDATE consent_forms
SET name = $3, description = $4, active = $5, form_config = $6, purposes = $7, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, active, form_config, purposes, created_at, updated_at
`

type UpdateConsentFormParams struct {
	ID             pgtype.UUID   `json:"id"`
	OrganizationID pgtype.UUID   `json:"organization_id"`
	Name           string        `json:"name"`
	Description    pgtype.Text   `json:"description"`
	Active         pgtype.Bool   `json:"active"`
	FormConfig     []byte        `json:"form_config"`
	Purposes       []pgtype.UUID `json:"purposes"`
}

func (q *Queries) UpdateConsentForm(ctx context.Context, arg UpdateConsentFormParams) (ConsentForm, error) {
	row := q.db.QueryRow(ctx, updateConsentForm,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.Active,
		arg.FormConfig,
		arg.Purposes,
	)
	var i ConsentForm
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.FormConfig,
		&i.Purposes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
