// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consent_receipts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordConsentReceipt = `-- name: RecordConsentReceipt :one
INSERT INTO consent_receipts (
    organization_id,
    domain,
    anonymous_id,
    consents,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, organization_id, domain, anonymous_id, consents, ip_address, user_agent, created_at
`

type RecordConsentReceiptParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Domain         string      `json:"domain"`
	AnonymousID    string      `json:"anonymous_id"`
	Consents       []byte      `json:"consents"`
	IpAddress      pgtype.Text `json:"ip_address"`
	UserAgent      pgtype.Text `json:"user_agent"`
}

func (q *Queries) RecordConsentReceipt(ctx context.Context, arg RecordConsentReceiptParams) (ConsentReceipt, error) {
	row := q.db.QueryRow(ctx, recordConsentReceipt,
		arg.OrganizationID,
		arg.Domain,
		arg.AnonymousID,
		arg.Consents,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i ConsentReceipt
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Domain,
		&i.AnonymousID,
		&i.Consents,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}
