// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ── Cookie Consents ──────────────────────────────────────

const insertCookieConsent = `-- name: InsertCookieConsent :exec
INSERT INTO cookie_consents (
    organization_id,
    anonymous_id,
    consents,
    ip_address,
    user_agent
) VALUES (
    $1, $2, $3, $4, $5
)`

type InsertCookieConsentParams struct {
	OrganizationID pgtype.UUID
	AnonymousID    pgtype.Text
	Consents       []byte
	IpAddress      pgtype.Text
	UserAgent      pgtype.Text
}

func (q *Queries) InsertCookieConsent(ctx context.Context, arg InsertCookieConsentParams) error {
	_, err := q.db.Exec(ctx, insertCookieConsent,
		arg.OrganizationID,
		arg.AnonymousID,
		arg.Consents,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
