// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// ── Cookie Banners ─────────────────────────────────────

const createCookieBanner = `-- name: CreateCookieBanner :one
INSERT INTO cookie_banners (
    id, organization_id, domain, name, title, message,
    accept_button_text, reject_button_text, settings_button_text,
    theme, position, active, config
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, organization_id, domain, name, title, message,
  accept_button_text, reject_button_text, settings_button_text,
  theme, position, active, config, created_at, updated_at`

type CreateCookieBannerParams struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	Domain             string
	Name               pgtype.Text
	Title              pgtype.Text
	Message            pgtype.Text
	AcceptButtonText   pgtype.Text
	RejectButtonText   pgtype.Text
	SettingsButtonText pgtype.Text
	Theme              pgtype.Text
	Position           pgtype.Text
	Active             pgtype.Bool
	Config             []byte
}

func (q *Queries) CreateCookieBanner(ctx context.Context, arg CreateCookieBannerParams) (CookieBanner, error) {
	row := q.db.QueryRow(ctx, createCookieBanner,
		arg.ID, arg.OrganizationID, arg.Domain, arg.Name, arg.Title, arg.Message,
		arg.AcceptButtonText, arg.RejectButtonText, arg.SettingsButtonText,
		arg.Theme, arg.Position, arg.Active, arg.Config,
	)
	var i CookieBanner
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Domain, &i.Name, &i.Title, &i.Message,
		&i.AcceptButtonText, &i.RejectButtonText, &i.SettingsButtonText,
		&i.Theme, &i.Position, &i.Active, &i.Config, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getCookieBanner = `-- name: GetCookieBanner :one
SELECT id, organization_id, domain, name, title, message,
  accept_button_text, reject_button_text, settings_button_text,
  theme, position, active, config, created_at, updated_at
FROM cookie_banners WHERE id = $1 AND organization_id = $2`

type GetCookieBannerParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetCookieBanner(ctx context.Context, arg GetCookieBannerParams) (CookieBanner, error) {
	row := q.db.QueryRow(ctx, getCookieBanner, arg.ID, arg.OrganizationID)
	var i CookieBanner
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Domain, &i.Name, &i.Title, &i.Message,
		&i.AcceptButtonText, &i.RejectButtonText, &i.SettingsButtonText,
		&i.Theme, &i.Position, &i.Active, &i.Config, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getCookieBannerByDomain = `-- name: GetCookieBannerByDomain :one
SELECT id, organization_id, domain, name, title, message,
  accept_button_text, reject_button_text, settings_button_text,
  theme, position, active, config, created_at, updated_at
FROM cookie_banners WHERE organization_id = $1 AND domain = $2`

type GetCookieBannerByDomainParams struct {
	OrganizationID pgtype.UUID
	Domain         string
}

func (q *Queries) GetCookieBannerByDomain(ctx context.Context, arg GetCookieBannerByDomainParams) (CookieBanner, error) {
	row := q.db.QueryRow(ctx, getCookieBannerByDomain, arg.OrganizationID, arg.Domain)
	var i CookieBanner
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Domain, &i.Name, &i.Title, &i.Message,
		&i.AcceptButtonText, &i.RejectButtonText, &i.SettingsButtonText,
		&i.Theme, &i.Position, &i.Active, &i.Config, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listCookieBanners = `-- name: ListCookieBanners :many
SELECT id, organization_id, domain, name, title, message,
  accept_button_text, reject_button_text, settings_button_text,
  theme, position, active, config, created_at, updated_at
FROM cookie_banners WHERE organization_id = $1 ORDER BY created_at DESC`

func (q *Queries) ListCookieBanners(ctx context.Context, organizationID interface{}) ([]CookieBanner, error) {
	rows, err := q.db.Query(ctx, listCookieBanners, organizationID)
	if err != nil {
		return nil, err
	}
	pgRows := rows.(pgx.Rows)
	defer pgRows.Close()
	var items []CookieBanner
	for pgRows.Next() {
		var i CookieBanner
		if err := pgRows.Scan(
			&i.ID, &i.OrganizationID, &i.Domain, &i.Name, &i.Title, &i.Message,
			&i.AcceptButtonText, &i.RejectButtonText, &i.SettingsButtonText,
			&i.Theme, &i.Position, &i.Active, &i.Config, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, pgRows.Err()
}

const updateCookieBanner = `-- name: UpdateCookieBanner :one
UPDATE cookie_banners
SET name=$3, title=$4, message=$5,
    accept_button_text=$6, reject_button_text=$7, settings_button_text=$8,
    theme=$9, position=$10, active=$11, config=$12, updated_at=NOW()
WHERE id=$1 AND organization_id=$2
RETURNING id, organization_id, domain, name, title, message,
  accept_button_text, reject_button_text, settings_button_text,
  theme, position, active, config, created_at, updated_at`

type UpdateCookieBannerParams struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	Name               pgtype.Text
	Title              pgtype.Text
	Message            pgtype.Text
	AcceptButtonText   pgtype.Text
	RejectButtonText   pgtype.Text
	SettingsButtonText pgtype.Text
	Theme              pgtype.Text
	Position           pgtype.Text
	Active             pgtype.Bool
	Config             []byte
}

func (q *Queries) UpdateCookieBanner(ctx context.Context, arg UpdateCookieBannerParams) (CookieBanner, error) {
	row := q.db.QueryRow(ctx, updateCookieBanner,
		arg.ID, arg.OrganizationID, arg.Name, arg.Title, arg.Message,
		arg.AcceptButtonText, arg.RejectButtonText, arg.SettingsButtonText,
		arg.Theme, arg.Position, arg.Active, arg.Config,
	)
	var i CookieBanner
	err := row.(pgx.Row).Scan(
		&i.ID, &i.OrganizationID, &i.Domain, &i.Name, &i.Title, &i.Message,
		&i.AcceptButtonText, &i.RejectButtonText, &i.SettingsButtonText,
		&i.Theme, &i.Position, &i.Active, &i.Config, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteCookieBanner = `-- name: DeleteCookieBanner :exec
DELETE FROM cookie_banners WHERE id=$1 AND organization_id=$2`

type DeleteCookieBannerParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) DeleteCookieBanner(ctx context.Context, arg DeleteCookieBannerParams) error {
	_, err := q.db.Exec(ctx, deleteCookieBanner, arg.ID, arg.OrganizationID)
	return err
}
