// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dpias.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDPIA = `-- name: CreateDPIA :one
INSERT INTO dpias (id, organization_id, name, vendor_id, status, risk_level, form_data)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, name, vendor_id, status, risk_level, form_data, created_at, updated_at
`

type CreateDPIAParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	VendorID       pgtype.UUID
	Status         pgtype.Text
	RiskLevel      pgtype.Text
	FormData       []byte
}

func (q *Queries) CreateDPIA(ctx context.Context, arg CreateDPIAParams) (Dpia, error) {
	row := q.db.QueryRow(ctx, createDPIA,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.VendorID,
		arg.Status,
		arg.RiskLevel,
		arg.FormData,
	)
	var i Dpia
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.VendorID,
		&i.Status,
		&i.RiskLevel,
		&i.FormData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDPIA = `-- name: GetDPIA :one
SELECT id, organization_id, name, vendor_id, status, risk_level, form_data, created_at, updated_at FROM dpias
WHERE id = $1 AND organization_id = $2
`

type GetDPIAParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetDPIA(ctx context.Context, arg GetDPIAParams) (Dpia, error) {
	row := q.db.QueryRow(ctx, getDPIA, arg.ID, arg.OrganizationID)
	var i Dpia
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.VendorID,
		&i.Status,
		&i.RiskLevel,
		&i.FormData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDPIAs = `-- name: ListDPIAs :many
SELECT id, organization_id, name, vendor_id, status, risk_level, form_data, created_at, updated_at FROM dpias
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDPIAs(ctx context.Context, organizationID pgtype.UUID) ([]Dpia, error) {
	rows, err := q.db.Query(ctx, listDPIAs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dpia
	for rows.Next() {
		var i Dpia
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.VendorID,
			&i.Status,
			&i.RiskLevel,
			&i.FormData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDPIA = `-- name: UpdateDPIA :one
UPDATE dpias
SET name = $3, vendor_id = $4, status = $5, risk_level = $6, form_data = $7, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, vendor_id, status, risk_level, form_data, created_at, updated_at
`

type UpdateDPIAParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	VendorID       pgtype.UUID
	Status         pgtype.Text
	RiskLevel      pgtype.Text
	FormData       []byte
}

func (q *Queries) UpdateDPIA(ctx context.Context, arg UpdateDPIAParams) (Dpia, error) {
	row := q.db.QueryRow(ctx, updateDPIA,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.VendorID,
		arg.Status,
		arg.RiskLevel,
		arg.FormData,
	)
	var i Dpia
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.VendorID,
		&i.Status,
		&i.RiskLevel,
		&i.FormData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
