// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grievances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGrievance = `-- name: CreateGrievance :one
INSERT INTO grievances (
    id, organization_id, reporter_email, issue_type, description, status, priority, resolution
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, reporter_email, issue_type, description, status, priority, resolution, created_at, updated_at
`

type CreateGrievanceParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	ReporterEmail  pgtype.Text
	IssueType      string
	Description    pgtype.Text
	Status         pgtype.Text
	Priority       pgtype.Text
	Resolution     pgtype.Text
}

func (q *Queries) CreateGrievance(ctx context.Context, arg CreateGrievanceParams) (Grievance, error) {
	row := q.db.QueryRow(ctx, createGrievance,
		arg.ID,
		arg.OrganizationID,
		arg.ReporterEmail,
		arg.IssueType,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Resolution,
	)
	var i Grievance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ReporterEmail,
		&i.IssueType,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGrievance = `-- name: GetGrievance :one
SELECT id, organization_id, reporter_email, issue_type, description, status, priority, resolution, created_at, updated_at FROM grievances
WHERE id = $1 AND organization_id = $2
`

type GetGrievanceParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetGrievance(ctx context.Context, arg GetGrievanceParams) (Grievance, error) {
	row := q.db.QueryRow(ctx, getGrievance, arg.ID, arg.OrganizationID)
	var i Grievance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ReporterEmail,
		&i.IssueType,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGrievances = `-- name: ListGrievances :many
SELECT id, organization_id, reporter_email, issue_type, description, status, priority, resolution, created_at, updated_at FROM grievances
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListGrievances(ctx context.Context, organizationID pgtype.UUID) ([]Grievance, error) {
	rows, err := q.db.Query(ctx, listGrievances, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Grievance
	for rows.Next() {
		var i Grievance
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ReporterEmail,
			&i.IssueType,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrievance = `-- name: UpdateGrievance :one
UPDATE grievances
SET status = $3, resolution = $4, priority = $5, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, reporter_email, issue_type, description, status, priority, resolution, created_at, updated_at
`

type UpdateGrievanceParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Status         pgtype.Text
	Resolution     pgtype.Text
	Priority       pgtype.Text
}

func (q *Queries) UpdateGrievance(ctx context.Context, arg UpdateGrievanceParams) (Grievance, error) {
	row := q.db.QueryRow(ctx, updateGrievance,
		arg.ID,
		arg.OrganizationID,
		arg.Status,
		arg.Resolution,
		arg.Priority,
	)
	var i Grievance
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ReporterEmail,
		&i.IssueType,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
