// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMagicToken = `-- name: CreateMagicToken :one
INSERT INTO magic_tokens (
    id, email, token, expires_at
) VALUES ($1, $2, $3, $4)
RETURNING id, email, token, expires_at, used_at, created_at
`

type CreateMagicTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMagicToken(ctx context.Context, arg CreateMagicTokenParams) (MagicToken, error) {
	row := q.db.QueryRow(ctx, createMagicToken,
		arg.ID,
		arg.Email,
		arg.Token,
		arg.ExpiresAt,
	)
	var i MagicToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMagicToken = `-- name: GetMagicToken :one
SELECT id, email, token, expires_at, used_at, created_at FROM magic_tokens
WHERE token = $1 AND used_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetMagicToken(ctx context.Context, token string) (MagicToken, error) {
	row := q.db.QueryRow(ctx, getMagicToken, token)
	var i MagicToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markMagicTokenUsed = `-- name: MarkMagicTokenUsed :exec
UPDATE magic_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkMagicTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMagicTokenUsed, id)
	return err
}
