// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CookieBanner struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	Domain             string
	Name               pgtype.Text
	Title              pgtype.Text
	Message            pgtype.Text
	AcceptButtonText   pgtype.Text
	RejectButtonText   pgtype.Text
	SettingsButtonText pgtype.Text
	Theme              pgtype.Text
	Position           pgtype.Text
	Active             pgtype.Bool
	Config             []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Purpose struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Description    pgtype.Text
	LegalBasis     pgtype.Text
	Active         pgtype.Bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type ConsentForm struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Description    pgtype.Text
	Active         pgtype.Bool
	FormConfig     []byte
	Purposes       []pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Dpia struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	VendorID       pgtype.UUID
	Status         pgtype.Text
	RiskLevel      pgtype.Text
	FormData       []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Ropa struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	Name               string
	ProcessingActivity pgtype.Text
	LegalBasis         pgtype.Text
	DataCategories     []string
	Status             pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type PrivacyRequest struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Type           string
	Status         pgtype.Text
	RequesterEmail pgtype.Text
	RequesterName  pgtype.Text
	Description    pgtype.Text
	Resolution     pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OutboxEvent struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
}
