// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nominees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNominee = `-- name: CreateNominee :one
INSERT INTO nominees (
    id, user_email, nominee_name, nominee_email, nominee_relation, status
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_email, nominee_name, nominee_email, nominee_relation, status, created_at, updated_at
`

type CreateNomineeParams struct {
	ID              pgtype.UUID `json:"id"`
	UserEmail       string      `json:"user_email"`
	NomineeName     string      `json:"nominee_name"`
	NomineeEmail    string      `json:"nominee_email"`
	NomineeRelation string      `json:"nominee_relation"`
	Status          pgtype.Text `json:"status"`
}

func (q *Queries) CreateNominee(ctx context.Context, arg CreateNomineeParams) (Nominee, error) {
	row := q.db.QueryRow(ctx, createNominee,
		arg.ID,
		arg.UserEmail,
		arg.NomineeName,
		arg.NomineeEmail,
		arg.NomineeRelation,
		arg.Status,
	)
	var i Nominee
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.NomineeName,
		&i.NomineeEmail,
		&i.NomineeRelation,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserNominees = `-- name: GetUserNominees :many
SELECT id, user_email, nominee_name, nominee_email, nominee_relation, status, created_at, updated_at FROM nominees
WHERE user_email = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserNominees(ctx context.Context, userEmail string) ([]Nominee, error) {
	rows, err := q.db.Query(ctx, getUserNominees, userEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nominee
	for rows.Next() {
		var i Nominee
		if err := rows.Scan(
			&i.ID,
			&i.UserEmail,
			&i.NomineeName,
			&i.NomineeEmail,
			&i.NomineeRelation,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNomineeStatus = `-- name: UpdateNomineeStatus :one
UPDATE nominees
SET status = $3, updated_at = NOW()
WHERE id = $1 AND user_email = $2
RETURNING id, user_email, nominee_name, nominee_email, nominee_relation, status, created_at, updated_at
`

type UpdateNomineeStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	UserEmail string      `json:"user_email"`
	Status    pgtype.Text `json:"status"`
}

func (q *Queries) UpdateNomineeStatus(ctx context.Context, arg UpdateNomineeStatusParams) (Nominee, error) {
	row := q.db.QueryRow(ctx, updateNomineeStatus, arg.ID, arg.UserEmail, arg.Status)
	var i Nominee
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.NomineeName,
		&i.NomineeEmail,
		&i.NomineeRelation,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
