// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrivacyRequest = `-- name: CreatePrivacyRequest :one
INSERT INTO privacy_requests (
    id, organization_id, type, status, requester_email, requester_name, description, due_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, organization_id, type, status, requester_email, requester_name, description, resolution, created_at, updated_at, due_date
`

type CreatePrivacyRequestParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Type           string             `json:"type"`
	Status         pgtype.Text        `json:"status"`
	RequesterEmail pgtype.Text        `json:"requester_email"`
	RequesterName  pgtype.Text        `json:"requester_name"`
	Description    pgtype.Text        `json:"description"`
	DueDate        pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreatePrivacyRequest(ctx context.Context, arg CreatePrivacyRequestParams) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, createPrivacyRequest,
		arg.ID,
		arg.OrganizationID,
		arg.Type,
		arg.Status,
		arg.RequesterEmail,
		arg.RequesterName,
		arg.Description,
		arg.DueDate,
	)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Type,
		&i.Status,
		&i.RequesterEmail,
		&i.RequesterName,
		&i.Description,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueDate,
	)
	return i, err
}

const getPrivacyRequest = `-- name: GetPrivacyRequest :one
SELECT id, organization_id, type, status, requester_email, requester_name, description, resolution, created_at, updated_at, due_date FROM privacy_requests
WHERE id = $1 AND organization_id = $2
`

type GetPrivacyRequestParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetPrivacyRequest(ctx context.Context, arg GetPrivacyRequestParams) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, getPrivacyRequest, arg.ID, arg.OrganizationID)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Type,
		&i.Status,
		&i.RequesterEmail,
		&i.RequesterName,
		&i.Description,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueDate,
	)
	return i, err
}

const listPrivacyRequests = `-- name: ListPrivacyRequests :many
SELECT id, organization_id, type, status, requester_email, requester_name, description, resolution, created_at, updated_at, due_date FROM privacy_requests
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPrivacyRequests(ctx context.Context, organizationID pgtype.UUID) ([]PrivacyRequest, error) {
	rows, err := q.db.Query(ctx, listPrivacyRequests, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivacyRequest
	for rows.Next() {
		var i PrivacyRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Type,
			&i.Status,
			&i.RequesterEmail,
			&i.RequesterName,
			&i.Description,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPrivacyRequests = `-- name: ListUserPrivacyRequests :many
SELECT id, organization_id, type, status, requester_email, requester_name, description, resolution, created_at, updated_at, due_date FROM privacy_requests
WHERE requester_email = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserPrivacyRequests(ctx context.Context, requesterEmail pgtype.Text) ([]PrivacyRequest, error) {
	rows, err := q.db.Query(ctx, listUserPrivacyRequests, requesterEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivacyRequest
	for rows.Next() {
		var i PrivacyRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Type,
			&i.Status,
			&i.RequesterEmail,
			&i.RequesterName,
			&i.Description,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DueDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrivacyRequest = `-- name: UpdatePrivacyRequest :one
UPDATE privacy_requests
SET status = $3, resolution = $4, due_date = $5, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, type, status, requester_email, requester_name, description, resolution, created_at, updated_at, due_date
`

type UpdatePrivacyRequestParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Status         pgtype.Text        `json:"status"`
	Resolution     pgtype.Text        `json:"resolution"`
	DueDate        pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdatePrivacyRequest(ctx context.Context, arg UpdatePrivacyRequestParams) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, updatePrivacyRequest,
		arg.ID,
		arg.OrganizationID,
		arg.Status,
		arg.Resolution,
		arg.DueDate,
	)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Type,
		&i.Status,
		&i.RequesterEmail,
		&i.RequesterName,
		&i.Description,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueDate,
	)
	return i, err
}
