// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purposes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurpose = `-- name: CreatePurpose :one
INSERT INTO purposes (id, organization_id, name, description, legal_basis, active, data_objects)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, name, description, legal_basis, active, created_at, updated_at, data_objects, cardinality(data_objects)::int AS data_objects_count
`

type CreatePurposeParams struct {
	ID             pgtype.UUID   `json:"id"`
	OrganizationID pgtype.UUID   `json:"organization_id"`
	Name           string        `json:"name"`
	Description    pgtype.Text   `json:"description"`
	LegalBasis     pgtype.Text   `json:"legal_basis"`
	Active         pgtype.Bool   `json:"active"`
	DataObjects    []pgtype.UUID `json:"data_objects"`
}

type CreatePurposeRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	LegalBasis       pgtype.Text        `json:"legal_basis"`
	Active           pgtype.Bool        `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DataObjects      []pgtype.UUID      `json:"data_objects"`
	DataObjectsCount int32              `json:"data_objects_count"`
}

func (q *Queries) CreatePurpose(ctx context.Context, arg CreatePurposeParams) (CreatePurposeRow, error) {
	row := q.db.QueryRow(ctx, createPurpose,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.LegalBasis,
		arg.Active,
		arg.DataObjects,
	)
	var i CreatePurposeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.LegalBasis,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataObjects,
		&i.DataObjectsCount,
	)
	return i, err
}

const getPurpose = `-- name: GetPurpose :one
SELECT id, organization_id, name, description, legal_basis, active, created_at, updated_at, data_objects, cardinality(data_objects)::int AS data_objects_count FROM purposes
WHERE id = $1 AND organization_id = $2
`

type GetPurposeParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetPurposeRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	LegalBasis       pgtype.Text        `json:"legal_basis"`
	Active           pgtype.Bool        `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DataObjects      []pgtype.UUID      `json:"data_objects"`
	DataObjectsCount int32              `json:"data_objects_count"`
}

func (q *Queries) GetPurpose(ctx context.Context, arg GetPurposeParams) (GetPurposeRow, error) {
	row := q.db.QueryRow(ctx, getPurpose, arg.ID, arg.OrganizationID)
	var i GetPurposeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.LegalBasis,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataObjects,
		&i.DataObjectsCount,
	)
	return i, err
}

const listPurposes = `-- name: ListPurposes :many
SELECT id, organization_id, name, description, legal_basis, active, created_at, updated_at, data_objects, cardinality(data_objects)::int AS data_objects_count FROM purposes
WHERE organization_id = $1
ORDER BY name ASC
`

type ListPurposesRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	LegalBasis       pgtype.Text        `json:"legal_basis"`
	Active           pgtype.Bool        `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DataObjects      []pgtype.UUID      `json:"data_objects"`
	DataObjectsCount int32              `json:"data_objects_count"`
}

func (q *Queries) ListPurposes(ctx context.Context, organizationID pgtype.UUID) ([]ListPurposesRow, error) {
	rows, err := q.db.Query(ctx, listPurposes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurposesRow
	for rows.Next() {
		var i ListPurposesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.LegalBasis,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DataObjects,
			&i.DataObjectsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurpose = `-- name: UpdatePurpose :one
UPDATE purposes
SET name = $3, description = $4, legal_basis = $5, active = $6, data_objects = $7, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, legal_basis, active, created_at, updated_at, data_objects, cardinality(data_objects)::int AS data_objects_count
`

type UpdatePurposeParams struct {
	ID             pgtype.UUID   `json:"id"`
	OrganizationID pgtype.UUID   `json:"organization_id"`
	Name           string        `json:"name"`
	Description    pgtype.Text   `json:"description"`
	LegalBasis     pgtype.Text   `json:"legal_basis"`
	Active         pgtype.Bool   `json:"active"`
	DataObjects    []pgtype.UUID `json:"data_objects"`
}

type UpdatePurposeRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	LegalBasis       pgtype.Text        `json:"legal_basis"`
	Active           pgtype.Bool        `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DataObjects      []pgtype.UUID      `json:"data_objects"`
	DataObjectsCount int32              `json:"data_objects_count"`
}

func (q *Queries) UpdatePurpose(ctx context.Context, arg UpdatePurposeParams) (UpdatePurposeRow, error) {
	row := q.db.QueryRow(ctx, updatePurpose,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.LegalBasis,
		arg.Active,
		arg.DataObjects,
	)
	var i UpdatePurposeRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.LegalBasis,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DataObjects,
		&i.DataObjectsCount,
	)
	return i, err
}
