// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purposes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurpose = `-- name: CreatePurpose :one
INSERT INTO purposes (id, organization_id, name, description, legal_basis, active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, name, description, legal_basis, active, created_at, updated_at
`

type CreatePurposeParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Description    pgtype.Text
	LegalBasis     pgtype.Text
	Active         pgtype.Bool
}

func (q *Queries) CreatePurpose(ctx context.Context, arg CreatePurposeParams) (Purpose, error) {
	row := q.db.QueryRow(ctx, createPurpose,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.LegalBasis,
		arg.Active,
	)
	var i Purpose
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.LegalBasis,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurpose = `-- name: GetPurpose :one
SELECT id, organization_id, name, description, legal_basis, active, created_at, updated_at FROM purposes
WHERE id = $1 AND organization_id = $2
`

type GetPurposeParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetPurpose(ctx context.Context, arg GetPurposeParams) (Purpose, error) {
	row := q.db.QueryRow(ctx, getPurpose, arg.ID, arg.OrganizationID)
	var i Purpose
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.LegalBasis,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPurposes = `-- name: ListPurposes :many
SELECT id, organization_id, name, description, legal_basis, active, created_at, updated_at FROM purposes
WHERE organization_id = $1
ORDER BY name ASC
`

func (q *Queries) ListPurposes(ctx context.Context, organizationID pgtype.UUID) ([]Purpose, error) {
	rows, err := q.db.Query(ctx, listPurposes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Purpose
	for rows.Next() {
		var i Purpose
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.LegalBasis,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurpose = `-- name: UpdatePurpose :one
UPDATE purposes
SET name = $3, description = $4, legal_basis = $5, active = $6, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, description, legal_basis, active, created_at, updated_at
`

type UpdatePurposeParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Description    pgtype.Text
	LegalBasis     pgtype.Text
	Active         pgtype.Bool
}

func (q *Queries) UpdatePurpose(ctx context.Context, arg UpdatePurposeParams) (Purpose, error) {
	row := q.db.QueryRow(ctx, updatePurpose,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.LegalBasis,
		arg.Active,
	)
	var i Purpose
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.LegalBasis,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
