// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import "context"

type Querier interface {
	// Cookie Banners
	CreateCookieBanner(ctx context.Context, arg CreateCookieBannerParams) (CookieBanner, error)
	GetCookieBanner(ctx context.Context, arg GetCookieBannerParams) (CookieBanner, error)
	GetCookieBannerByDomain(ctx context.Context, arg GetCookieBannerByDomainParams) (CookieBanner, error)
	ListCookieBanners(ctx context.Context, organizationID interface{}) ([]CookieBanner, error)
	UpdateCookieBanner(ctx context.Context, arg UpdateCookieBannerParams) (CookieBanner, error)
	DeleteCookieBanner(ctx context.Context, arg DeleteCookieBannerParams) error

	// Purposes
	CreatePurpose(ctx context.Context, arg CreatePurposeParams) (Purpose, error)
	GetPurpose(ctx context.Context, arg GetPurposeParams) (Purpose, error)
	ListPurposes(ctx context.Context, organizationID interface{}) ([]Purpose, error)
	UpdatePurpose(ctx context.Context, arg UpdatePurposeParams) (Purpose, error)

	// Consent Forms
	CreateConsentForm(ctx context.Context, arg CreateConsentFormParams) (ConsentForm, error)
	GetConsentForm(ctx context.Context, arg GetConsentFormParams) (ConsentForm, error)
	ListConsentForms(ctx context.Context, organizationID interface{}) ([]ConsentForm, error)
	UpdateConsentForm(ctx context.Context, arg UpdateConsentFormParams) (ConsentForm, error)

	// DPIAs
	CreateDPIA(ctx context.Context, arg CreateDPIAParams) (Dpia, error)
	GetDPIA(ctx context.Context, arg GetDPIAParams) (Dpia, error)
	ListDPIAs(ctx context.Context, organizationID interface{}) ([]Dpia, error)
	UpdateDPIA(ctx context.Context, arg UpdateDPIAParams) (Dpia, error)

	// ROPAs
	CreateROPA(ctx context.Context, arg CreateROPAParams) (Ropa, error)
	GetROPA(ctx context.Context, arg GetROPAParams) (Ropa, error)
	ListROPAs(ctx context.Context, organizationID interface{}) ([]Ropa, error)
	UpdateROPA(ctx context.Context, arg UpdateROPAParams) (Ropa, error)

	// Privacy Requests
	CreatePrivacyRequest(ctx context.Context, arg CreatePrivacyRequestParams) (PrivacyRequest, error)
	GetPrivacyRequest(ctx context.Context, arg GetPrivacyRequestParams) (PrivacyRequest, error)
	ListPrivacyRequests(ctx context.Context, organizationID interface{}) ([]PrivacyRequest, error)
	UpdatePrivacyRequest(ctx context.Context, arg UpdatePrivacyRequestParams) (PrivacyRequest, error)

	// Outbox
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error

	// Cookie Consents (written by the NATS consent consumer)
	InsertCookieConsent(ctx context.Context, arg InsertCookieConsentParams) error
}

var _ Querier = (*Queries)(nil)
