// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ropas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createROPA = `-- name: CreateROPA :one
INSERT INTO ropas (id, organization_id, name, processing_activity, legal_basis, data_categories, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, name, processing_activity, legal_basis, data_categories, status, created_at, updated_at
`

type CreateROPAParams struct {
	ID                 pgtype.UUID `json:"id"`
	OrganizationID     pgtype.UUID `json:"organization_id"`
	Name               string      `json:"name"`
	ProcessingActivity pgtype.Text `json:"processing_activity"`
	LegalBasis         pgtype.Text `json:"legal_basis"`
	DataCategories     []string    `json:"data_categories"`
	Status             pgtype.Text `json:"status"`
}

func (q *Queries) CreateROPA(ctx context.Context, arg CreateROPAParams) (Ropa, error) {
	row := q.db.QueryRow(ctx, createROPA,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.ProcessingActivity,
		arg.LegalBasis,
		arg.DataCategories,
		arg.Status,
	)
	var i Ropa
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ProcessingActivity,
		&i.LegalBasis,
		&i.DataCategories,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getROPA = `-- name: GetROPA :one
SELECT id, organization_id, name, processing_activity, legal_basis, data_categories, status, created_at, updated_at FROM ropas
WHERE id = $1 AND organization_id = $2
`

type GetROPAParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetROPA(ctx context.Context, arg GetROPAParams) (Ropa, error) {
	row := q.db.QueryRow(ctx, getROPA, arg.ID, arg.OrganizationID)
	var i Ropa
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ProcessingActivity,
		&i.LegalBasis,
		&i.DataCategories,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listROPAs = `-- name: ListROPAs :many
SELECT id, organization_id, name, processing_activity, legal_basis, data_categories, status, created_at, updated_at FROM ropas
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListROPAs(ctx context.Context, organizationID pgtype.UUID) ([]Ropa, error) {
	rows, err := q.db.Query(ctx, listROPAs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ropa
	for rows.Next() {
		var i Ropa
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.ProcessingActivity,
			&i.LegalBasis,
			&i.DataCategories,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateROPA = `-- name: UpdateROPA :one
UPDATE ropas
SET name = $3, processing_activity = $4, legal_basis = $5,
    data_categories = $6, status = $7, updated_at = NOW()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, processing_activity, legal_basis, data_categories, status, created_at, updated_at
`

type UpdateROPAParams struct {
	ID                 pgtype.UUID `json:"id"`
	OrganizationID     pgtype.UUID `json:"organization_id"`
	Name               string      `json:"name"`
	ProcessingActivity pgtype.Text `json:"processing_activity"`
	LegalBasis         pgtype.Text `json:"legal_basis"`
	DataCategories     []string    `json:"data_categories"`
	Status             pgtype.Text `json:"status"`
}

func (q *Queries) UpdateROPA(ctx context.Context, arg UpdateROPAParams) (Ropa, error) {
	row := q.db.QueryRow(ctx, updateROPA,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.ProcessingActivity,
		arg.LegalBasis,
		arg.DataCategories,
		arg.Status,
	)
	var i Ropa
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ProcessingActivity,
		&i.LegalBasis,
		&i.DataCategories,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
