upstreams:
  - id: abc-service-upstream
    nodes:
      "abc-service:8080": 1
    type: roundrobin

  - id: def-service-upstream
    nodes:
      "def-service:8080": 1
    type: roundrobin

  - id: iam-service-upstream
    nodes:
      "iam-service:8080": 1
    type: roundrobin

  - id: privacy-service-upstream
    nodes:
      "privacy-service:8080": 1
    type: roundrobin

  - id: discovery-service-upstream
    nodes:
      "discovery-service:8080": 1
    type: roundrobin

routes:
  # ─── ABC Service Routes (method-scoped for fine-grained authz) ───
  # Fixes FLAW-1.3: the original single route used "item:read" for ALL
  # methods, meaning users with read-only permission could create/mutate/delete.
  - id: abc-domain-read
    uri: /api/abc/*
    methods: ["GET", "OPTIONS"]
    upstream_id: abc-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "item:read"}'

  - id: abc-domain-write
    uri: /api/abc/*
    methods: ["POST", "PATCH", "PUT"]
    upstream_id: abc-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "item:write"}'

  - id: abc-domain-delete
    uri: /api/abc/*
    methods: ["DELETE"]
    upstream_id: abc-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "item:delete"}'

  # ─── DEF Service Routes ───────────────────────────────────
  - id: def-domain-route
    uri: /api/def/*
    upstream_id: def-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "task:read"}'

  # ─── IAM Service Routes (admin only) ─────────────────────
  - id: iam-domain-route
    uri: /api/iam/*
    upstream_id: iam-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "iam:manage"}'

  # ─── Public Swagger UI Routes (no auth) ──────────────────
  - id: abc-swagger-route
    uri: /api/abc/swagger/*
    priority: 10
    upstream_id: abc-service-upstream
    plugins:
      proxy-rewrite:
        regex_uri: ["^/api/abc/(.*)", "/$1"]
      cors:
        allow_origins: "*"
        allow_methods: "GET,OPTIONS"

  - id: iam-swagger-route
    uri: /api/iam/swagger/*
    priority: 10
    upstream_id: iam-service-upstream
    plugins:
      proxy-rewrite:
        regex_uri: ["^/api/iam/(.*)", "/$1"]
      cors:
        allow_origins: "*"
        allow_methods: "GET,OPTIONS"

  # ─── Privacy Service Routes (method-scoped for fine-grained authz) ───
  - id: privacy-domain-read
    uri: /api/privacy/*
    methods: ["GET", "OPTIONS"]
    upstream_id: privacy-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        regex_uri: ["^/api/privacy/(.*)", "/$1"]
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "privacy:read"}'

  - id: privacy-domain-write
    uri: /api/privacy/*
    methods: ["POST", "PATCH", "PUT"]
    upstream_id: privacy-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        regex_uri: ["^/api/privacy/(.*)", "/$1"]
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "privacy:write"}'

  - id: privacy-domain-delete
    uri: /api/privacy/*
    methods: ["DELETE"]
    upstream_id: privacy-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        regex_uri: ["^/api/privacy/(.*)", "/$1"]
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""
      ext-plugin-pre-req:
        conf:
          - name: "authz"
            value: '{"permission_slug": "privacy:delete"}'

  # ─── Discovery Service Routes (Data Intelligence) ──────────────────
  - id: discovery-domain-read
    uri: /api/discovery/*
    methods: ["GET", "OPTIONS"]
    upstream_id: discovery-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        regex_uri: ["^/api/discovery/(.*)", "/$1"]
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""

  - id: discovery-domain-write
    uri: /api/discovery/*
    methods: ["POST", "PATCH", "PUT"]
    upstream_id: discovery-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        regex_uri: ["^/api/discovery/(.*)", "/$1"]
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""

  - id: discovery-domain-delete
    uri: /api/discovery/*
    methods: ["DELETE"]
    upstream_id: discovery-service-upstream
    plugins:
      limit-count:
        count: 100
        time_window: 60
        rejected_code: 429
        key: "http_x_organization_id"
      cors:
        allow_origins: "http://localhost:5173"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,X-Organization-Id,Content-Type"
        allow_credential: true
      proxy-rewrite:
        regex_uri: ["^/api/discovery/(.*)", "/$1"]
        headers:
          set:
            X-Internal-User-Id: ""
            X-Internal-Org-Id: ""
            X-Internal-Permissions: ""

#END
