// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Vendor struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Name             string
	ContactEmail     pgtype.Text
	ComplianceStatus pgtype.Text
	RiskLevel        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Framework struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Version        string
	CreatedAt      pgtype.Timestamptz
}

type Assessment struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	VendorID       pgtype.UUID
	FrameworkID    pgtype.UUID
	Status         pgtype.Text
	Score          pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Dpa struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	VendorID       pgtype.UUID
	Status         string
	SignedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// DpaDataScope is the raw join record from the dpa_data_scope table.
type DpaDataScope struct {
	DpaID        pgtype.UUID
	DictionaryID pgtype.UUID
	Justification pgtype.Text
}

// DpaDataScopeRow is returned by ListDPADataScope (join with replicated_data_dictionary).
type DpaDataScopeRow struct {
	DpaID        pgtype.UUID
	DictionaryID pgtype.UUID
	Justification pgtype.Text
	DictName     string
	Sensitivity  string
}

type ReplicatedDataDictionary struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Sensitivity    string
	Active         bool
	UpdatedAt      pgtype.Timestamptz
}

type OutboxEvent struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
}
