// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assessment struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	VendorID       pgtype.UUID
	FrameworkID    pgtype.UUID
	Status         pgtype.Text
	Score          pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	AuditCycleID   pgtype.UUID
}

type AssessmentAnswer struct {
	ID            pgtype.UUID
	AssessmentID  pgtype.UUID
	QuestionID    pgtype.UUID
	AnswerText    pgtype.Text
	AnswerOptions []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AuditCycle struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Status         pgtype.Text
	StartDate      pgtype.Timestamptz
	EndDate        pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Dpa struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	VendorID       pgtype.UUID
	Status         string
	SignedAt       pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type DpaDataScope struct {
	DpaID         pgtype.UUID
	DictionaryID  pgtype.UUID
	Justification pgtype.Text
}

type Framework struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Version        string
	CreatedAt      pgtype.Timestamptz
	Description    pgtype.Text
	UpdatedAt      pgtype.Timestamptz
}

type FrameworkQuestion struct {
	ID           pgtype.UUID
	FrameworkID  pgtype.UUID
	QuestionText string
	QuestionType pgtype.Text
	Options      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OutboxEvent struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AggregateType  string
	AggregateID    string
	EventType      string
	Payload        []byte
	CreatedAt      pgtype.Timestamptz
}

type ReplicatedDataDictionary struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	Sensitivity    string
	Active         bool
	UpdatedAt      pgtype.Timestamptz
}

type Vendor struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Name             string
	ContactEmail     pgtype.Text
	ComplianceStatus pgtype.Text
	RiskLevel        pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
