// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Vendors
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	GetVendor(ctx context.Context, arg GetVendorParams) (Vendor, error)
	ListVendors(ctx context.Context, organizationID pgtype.UUID) ([]Vendor, error)
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
	DeleteVendor(ctx context.Context, arg DeleteVendorParams) error

	// Frameworks
	CreateFramework(ctx context.Context, arg CreateFrameworkParams) (Framework, error)
	GetFramework(ctx context.Context, arg GetFrameworkParams) (Framework, error)
	ListFrameworks(ctx context.Context, organizationID pgtype.UUID) ([]Framework, error)

	// Assessments
	CreateAssessment(ctx context.Context, arg CreateAssessmentParams) (Assessment, error)
	GetAssessment(ctx context.Context, arg GetAssessmentParams) (Assessment, error)
	ListAssessmentsByVendor(ctx context.Context, arg ListAssessmentsByVendorParams) ([]Assessment, error)
	UpdateAssessmentStatus(ctx context.Context, arg UpdateAssessmentStatusParams) (Assessment, error)

	// DPAs
	CreateDPA(ctx context.Context, arg CreateDPAParams) (Dpa, error)
	GetDPA(ctx context.Context, arg GetDPAParams) (Dpa, error)
	ListDPAsByVendor(ctx context.Context, arg ListDPAsByVendorParams) ([]Dpa, error)
	UpdateDPAStatus(ctx context.Context, arg UpdateDPAStatusParams) (Dpa, error)
	AddDPADataScope(ctx context.Context, arg AddDPADataScopeParams) error
	ListDPADataScope(ctx context.Context, dpaID pgtype.UUID) ([]DpaDataScopeRow, error)

	// Replicated Data Dictionary
	UpsertReplicatedDictionary(ctx context.Context, arg UpsertReplicatedDictionaryParams) error
	DeleteReplicatedDictionary(ctx context.Context, id pgtype.UUID) error
	GetReplicatedDictionaryItem(ctx context.Context, id pgtype.UUID) (ReplicatedDataDictionary, error)
	ListReplicatedDictionary(ctx context.Context, organizationID pgtype.UUID) ([]ReplicatedDataDictionary, error)

	// Outbox
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
}

var _ Querier = (*Queries)(nil)
