// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertCookies implements pgx.CopyFromSource.
type iteratorForInsertCookies struct {
	rows                 []InsertCookiesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCookies) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCookies) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].ScanID,
		r.rows[0].Name,
		r.rows[0].Domain,
		r.rows[0].Path,
		r.rows[0].Value,
		r.rows[0].Expiration,
		r.rows[0].Secure,
		r.rows[0].HttpOnly,
		r.rows[0].SameSite,
		r.rows[0].Source,
		r.rows[0].Category,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForInsertCookies) Err() error {
	return nil
}

func (q *Queries) InsertCookies(ctx context.Context, arg []InsertCookiesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"scanned_cookies"}, []string{"id", "scan_id", "name", "domain", "path", "value", "expiration", "secure", "http_only", "same_site", "source", "category", "description"}, &iteratorForInsertCookies{rows: arg})
}
