// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CookieScan struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Url         string
	Status      string
	Error       pgtype.Text
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ScannedCookie struct {
	ID          pgtype.UUID
	ScanID      pgtype.UUID
	Name        string
	Domain      pgtype.Text
	Path        pgtype.Text
	Value       pgtype.Text
	Expiration  pgtype.Timestamptz
	Secure      bool
	HttpOnly    bool
	SameSite    pgtype.Text
	Source      string
	Category    string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
}
