// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateScan(ctx context.Context, arg CreateScanParams) (CookieScan, error)
	GetCookiesByScan(ctx context.Context, scanID pgtype.UUID) ([]ScannedCookie, error)
	GetScan(ctx context.Context, id pgtype.UUID) (CookieScan, error)
	InsertCookies(ctx context.Context, arg []InsertCookiesParams) (int64, error)
	ListScans(ctx context.Context, arg ListScansParams) ([]CookieScan, error)
	UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) (CookieScan, error)
}

var _ Querier = (*Queries)(nil)
