// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScan = `-- name: CreateScan :one
INSERT INTO cookie_scans (id, tenant_id, url, status, created_at, updated_at)
VALUES ($1, $2, $3, 'pending', NOW(), NOW())
RETURNING id, tenant_id, url, status, error, started_at, completed_at, created_at, updated_at
`

type CreateScanParams struct {
	ID       pgtype.UUID
	TenantID pgtype.UUID
	Url      string
}

func (q *Queries) CreateScan(ctx context.Context, arg CreateScanParams) (CookieScan, error) {
	row := q.db.QueryRow(ctx, createScan, arg.ID, arg.TenantID, arg.Url)
	var i CookieScan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCookiesByScan = `-- name: GetCookiesByScan :many
SELECT id, scan_id, name, domain, path, value, expiration, secure, http_only, same_site, source, category, description, created_at FROM scanned_cookies
WHERE scan_id = $1
ORDER BY category, name
`

func (q *Queries) GetCookiesByScan(ctx context.Context, scanID pgtype.UUID) ([]ScannedCookie, error) {
	rows, err := q.db.Query(ctx, getCookiesByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScannedCookie
	for rows.Next() {
		var i ScannedCookie
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.Name,
			&i.Domain,
			&i.Path,
			&i.Value,
			&i.Expiration,
			&i.Secure,
			&i.HttpOnly,
			&i.SameSite,
			&i.Source,
			&i.Category,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScan = `-- name: GetScan :one
SELECT id, tenant_id, url, status, error, started_at, completed_at, created_at, updated_at FROM cookie_scans WHERE id = $1
`

func (q *Queries) GetScan(ctx context.Context, id pgtype.UUID) (CookieScan, error) {
	row := q.db.QueryRow(ctx, getScan, id)
	var i CookieScan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type InsertCookiesParams struct {
	ID          pgtype.UUID
	ScanID      pgtype.UUID
	Name        string
	Domain      pgtype.Text
	Path        pgtype.Text
	Value       pgtype.Text
	Expiration  pgtype.Timestamptz
	Secure      bool
	HttpOnly    bool
	SameSite    pgtype.Text
	Source      string
	Category    string
	Description pgtype.Text
}

const listScans = `-- name: ListScans :many
SELECT id, tenant_id, url, status, error, started_at, completed_at, created_at, updated_at FROM cookie_scans
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListScansParams struct {
	TenantID pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListScans(ctx context.Context, arg ListScansParams) ([]CookieScan, error) {
	rows, err := q.db.Query(ctx, listScans, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CookieScan
	for rows.Next() {
		var i CookieScan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanStatus = `-- name: UpdateScanStatus :one
UPDATE cookie_scans
SET
    status       = $2,
    error        = $3,
    started_at   = $4,
    completed_at = $5,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, tenant_id, url, status, error, started_at, completed_at, created_at, updated_at
`

type UpdateScanStatusParams struct {
	ID          pgtype.UUID
	Status      string
	Error       pgtype.Text
	StartedAt   pgtype.Timestamptz
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) UpdateScanStatus(ctx context.Context, arg UpdateScanStatusParams) (CookieScan, error) {
	row := q.db.QueryRow(ctx, updateScanStatus,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i CookieScan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
