// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationTemplate struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	Name             string
	SubjectTemplate  string
	BodyHtmlTemplate string
	CreatedAt        pgtype.Timestamptz
}

type Webhook struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	EndpointUrl      string
	SecretKey        string
	SubscribedEvents []string
	Active           pgtype.Bool
	CreatedAt        pgtype.Timestamptz
}

type DeliveryLog struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	DeliveryType   string
	Recipient      string
	Status         string
	ErrorMessage   pgtype.Text
	CreatedAt      pgtype.Timestamptz
}
