// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

// ── Notification Templates ───────────────────────────────────────────────

const createNotificationTemplate = `INSERT INTO notification_templates (organization_id, name, subject_template, body_html_template)
VALUES ($1, $2, $3, $4) RETURNING id, organization_id, name, subject_template, body_html_template, created_at`

type CreateNotificationTemplateParams struct {
	OrganizationID   pgtype.UUID
	Name             string
	SubjectTemplate  string
	BodyHtmlTemplate string
}

func (q *Queries) CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, createNotificationTemplate, arg.OrganizationID, arg.Name, arg.SubjectTemplate, arg.BodyHtmlTemplate)
	var i NotificationTemplate
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.SubjectTemplate, &i.BodyHtmlTemplate, &i.CreatedAt)
	return i, err
}

const getNotificationTemplate = `SELECT id, organization_id, name, subject_template, body_html_template, created_at FROM notification_templates WHERE id = $1 AND organization_id = $2`

type GetNotificationTemplateParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetNotificationTemplate(ctx context.Context, arg GetNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getNotificationTemplate, arg.ID, arg.OrganizationID)
	var i NotificationTemplate
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.SubjectTemplate, &i.BodyHtmlTemplate, &i.CreatedAt)
	return i, err
}

const getNotificationTemplateByName = `SELECT id, organization_id, name, subject_template, body_html_template, created_at FROM notification_templates WHERE organization_id = $1 AND name = $2`

type GetNotificationTemplateByNameParams struct {
	OrganizationID pgtype.UUID
	Name           string
}

func (q *Queries) GetNotificationTemplateByName(ctx context.Context, arg GetNotificationTemplateByNameParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getNotificationTemplateByName, arg.OrganizationID, arg.Name)
	var i NotificationTemplate
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.SubjectTemplate, &i.BodyHtmlTemplate, &i.CreatedAt)
	return i, err
}

const listNotificationTemplates = `SELECT id, organization_id, name, subject_template, body_html_template, created_at FROM notification_templates WHERE organization_id = $1 ORDER BY created_at DESC`

func (q *Queries) ListNotificationTemplates(ctx context.Context, organizationID interface{}) ([]NotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listNotificationTemplates, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationTemplate
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.SubjectTemplate, &i.BodyHtmlTemplate, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateNotificationTemplate = `UPDATE notification_templates SET subject_template = $3, body_html_template = $4 WHERE id = $1 AND organization_id = $2 RETURNING id, organization_id, name, subject_template, body_html_template, created_at`

type UpdateNotificationTemplateParams struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	SubjectTemplate  string
	BodyHtmlTemplate string
}

func (q *Queries) UpdateNotificationTemplate(ctx context.Context, arg UpdateNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, updateNotificationTemplate, arg.ID, arg.OrganizationID, arg.SubjectTemplate, arg.BodyHtmlTemplate)
	var i NotificationTemplate
	err := row.Scan(&i.ID, &i.OrganizationID, &i.Name, &i.SubjectTemplate, &i.BodyHtmlTemplate, &i.CreatedAt)
	return i, err
}

const deleteNotificationTemplate = `DELETE FROM notification_templates WHERE id = $1 AND organization_id = $2`

type DeleteNotificationTemplateParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) DeleteNotificationTemplate(ctx context.Context, arg DeleteNotificationTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationTemplate, arg.ID, arg.OrganizationID)
	return err
}

// ── Webhooks ─────────────────────────────────────────────────────────────

const createWebhook = `INSERT INTO webhooks (organization_id, endpoint_url, secret_key, subscribed_events)
VALUES ($1, $2, $3, $4) RETURNING id, organization_id, endpoint_url, secret_key, subscribed_events, active, created_at`

type CreateWebhookParams struct {
	OrganizationID   pgtype.UUID
	EndpointUrl      string
	SecretKey        string
	SubscribedEvents []string
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook, arg.OrganizationID, arg.EndpointUrl, arg.SecretKey, arg.SubscribedEvents)
	var i Webhook
	err := row.Scan(&i.ID, &i.OrganizationID, &i.EndpointUrl, &i.SecretKey, &i.SubscribedEvents, &i.Active, &i.CreatedAt)
	return i, err
}

const getWebhook = `SELECT id, organization_id, endpoint_url, secret_key, subscribed_events, active, created_at FROM webhooks WHERE id = $1 AND organization_id = $2`

type GetWebhookParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.ID, arg.OrganizationID)
	var i Webhook
	err := row.Scan(&i.ID, &i.OrganizationID, &i.EndpointUrl, &i.SecretKey, &i.SubscribedEvents, &i.Active, &i.CreatedAt)
	return i, err
}

const listWebhooks = `SELECT id, organization_id, endpoint_url, secret_key, subscribed_events, active, created_at FROM webhooks WHERE organization_id = $1 ORDER BY created_at DESC`

func (q *Queries) ListWebhooks(ctx context.Context, organizationID interface{}) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.EndpointUrl, &i.SecretKey, &i.SubscribedEvents, &i.Active, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const updateWebhook = `UPDATE webhooks SET endpoint_url = $2, secret_key = $3, subscribed_events = $4, active = $5 WHERE id = $1 RETURNING id, organization_id, endpoint_url, secret_key, subscribed_events, active, created_at`

type UpdateWebhookParams struct {
	ID               pgtype.UUID
	EndpointUrl      string
	SecretKey        string
	SubscribedEvents []string
	Active           pgtype.Bool
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook, arg.ID, arg.EndpointUrl, arg.SecretKey, arg.SubscribedEvents, arg.Active)
	var i Webhook
	err := row.Scan(&i.ID, &i.OrganizationID, &i.EndpointUrl, &i.SecretKey, &i.SubscribedEvents, &i.Active, &i.CreatedAt)
	return i, err
}

const deleteWebhook = `DELETE FROM webhooks WHERE id = $1 AND organization_id = $2`

type DeleteWebhookParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.OrganizationID)
	return err
}

const getActiveWebhooksByEvent = `SELECT id, organization_id, endpoint_url, secret_key, subscribed_events, active, created_at FROM webhooks WHERE active = true AND $1 = ANY(subscribed_events)`

func (q *Queries) GetActiveWebhooksByEvent(ctx context.Context, event string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, getActiveWebhooksByEvent, event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(&i.ID, &i.OrganizationID, &i.EndpointUrl, &i.SecretKey, &i.SubscribedEvents, &i.Active, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

// ── Delivery Logs ────────────────────────────────────────────────────────

const insertDeliveryLog = `INSERT INTO delivery_logs (organization_id, delivery_type, recipient, status, error_message) VALUES ($1, $2, $3, $4, $5)`

type InsertDeliveryLogParams struct {
	OrganizationID pgtype.UUID
	DeliveryType   string
	Recipient      string
	Status         string
	ErrorMessage   pgtype.Text
}

func (q *Queries) InsertDeliveryLog(ctx context.Context, arg InsertDeliveryLogParams) error {
	_, err := q.db.Exec(ctx, insertDeliveryLog, arg.OrganizationID, arg.DeliveryType, arg.Recipient, arg.Status, arg.ErrorMessage)
	return err
}
