// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import "context"

type Querier interface {
	// Notification Templates
	CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) (NotificationTemplate, error)
	GetNotificationTemplate(ctx context.Context, arg GetNotificationTemplateParams) (NotificationTemplate, error)
	GetNotificationTemplateByName(ctx context.Context, arg GetNotificationTemplateByNameParams) (NotificationTemplate, error)
	ListNotificationTemplates(ctx context.Context, organizationID interface{}) ([]NotificationTemplate, error)
	UpdateNotificationTemplate(ctx context.Context, arg UpdateNotificationTemplateParams) (NotificationTemplate, error)
	DeleteNotificationTemplate(ctx context.Context, arg DeleteNotificationTemplateParams) error

	// Webhooks
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error)
	ListWebhooks(ctx context.Context, organizationID interface{}) ([]Webhook, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error
	GetActiveWebhooksByEvent(ctx context.Context, event string) ([]Webhook, error)

	// Delivery Logs
	InsertDeliveryLog(ctx context.Context, arg InsertDeliveryLogParams) error
}

var _ Querier = (*Queries)(nil)
